namespace ModeMath

// Generated by tools/MathTableGen from latinmodern-math.otf and AMS-Capital-Blackboard-Bold.otf. Do not edit.

/// Positioning values from the MATH table, in font design units.
module MathConstants =
    [<Literal>]
    let UnitsPerEm = 1000f<du>
    [<Literal>]
    let ScriptPercentScaleDown = 70f
    [<Literal>]
    let ScriptScriptPercentScaleDown = 50f
    [<Literal>]
    let DelimitedSubFormulaMinHeight = 1300f<du>
    [<Literal>]
    let DisplayOperatorMinHeight = 1300f<du>
    [<Literal>]
    let MathLeading = 154f<du>
    [<Literal>]
    let AxisHeight = 250f<du>
    [<Literal>]
    let AccentBaseHeight = 450f<du>
    [<Literal>]
    let FlattenedAccentBaseHeight = 664f<du>
    [<Literal>]
    let SubscriptShiftDown = 247f<du>
    [<Literal>]
    let SubscriptTopMax = 344f<du>
    [<Literal>]
    let SubscriptBaselineDropMin = 200f<du>
    [<Literal>]
    let SuperscriptShiftUp = 363f<du>
    [<Literal>]
    let SuperscriptShiftUpCramped = 289f<du>
    [<Literal>]
    let SuperscriptBottomMin = 108f<du>
    [<Literal>]
    let SuperscriptBaselineDropMax = 250f<du>
    [<Literal>]
    let SubSuperscriptGapMin = 160f<du>
    [<Literal>]
    let SuperscriptBottomMaxWithSubscript = 344f<du>
    [<Literal>]
    let SpaceAfterScript = 56f<du>
    [<Literal>]
    let UpperLimitGapMin = 200f<du>
    [<Literal>]
    let UpperLimitBaselineRiseMin = 111f<du>
    [<Literal>]
    let LowerLimitGapMin = 167f<du>
    [<Literal>]
    let LowerLimitBaselineDropMin = 600f<du>
    [<Literal>]
    let StackTopShiftUp = 444f<du>
    [<Literal>]
    let StackTopDisplayStyleShiftUp = 677f<du>
    [<Literal>]
    let StackBottomShiftDown = 345f<du>
    [<Literal>]
    let StackBottomDisplayStyleShiftDown = 686f<du>
    [<Literal>]
    let StackGapMin = 120f<du>
    [<Literal>]
    let StackDisplayStyleGapMin = 280f<du>
    [<Literal>]
    let StretchStackTopShiftUp = 111f<du>
    [<Literal>]
    let StretchStackBottomShiftDown = 600f<du>
    [<Literal>]
    let StretchStackGapAboveMin = 200f<du>
    [<Literal>]
    let StretchStackGapBelowMin = 167f<du>
    [<Literal>]
    let FractionNumeratorShiftUp = 394f<du>
    [<Literal>]
    let FractionNumeratorDisplayStyleShiftUp = 677f<du>
    [<Literal>]
    let FractionDenominatorShiftDown = 345f<du>
    [<Literal>]
    let FractionDenominatorDisplayStyleShiftDown = 686f<du>
    [<Literal>]
    let FractionNumeratorGapMin = 40f<du>
    [<Literal>]
    let FractionNumDisplayStyleGapMin = 120f<du>
    [<Literal>]
    let FractionRuleThickness = 40f<du>
    [<Literal>]
    let FractionDenominatorGapMin = 40f<du>
    [<Literal>]
    let FractionDenomDisplayStyleGapMin = 120f<du>
    [<Literal>]
    let SkewedFractionHorizontalGap = 350f<du>
    [<Literal>]
    let SkewedFractionVerticalGap = 96f<du>
    [<Literal>]
    let OverbarVerticalGap = 120f<du>
    [<Literal>]
    let OverbarRuleThickness = 40f<du>
    [<Literal>]
    let OverbarExtraAscender = 40f<du>
    [<Literal>]
    let UnderbarVerticalGap = 120f<du>
    [<Literal>]
    let UnderbarRuleThickness = 40f<du>
    [<Literal>]
    let UnderbarExtraDescender = 40f<du>
    [<Literal>]
    let RadicalVerticalGap = 50f<du>
    [<Literal>]
    let RadicalDisplayStyleVerticalGap = 148f<du>
    [<Literal>]
    let RadicalRuleThickness = 40f<du>
    [<Literal>]
    let RadicalExtraAscender = 40f<du>
    [<Literal>]
    let RadicalKernBeforeDegree = 278f<du>
    [<Literal>]
    let RadicalKernAfterDegree = -556f<du>
    [<Literal>]
    let RadicalDegreeBottomRaisePercent = 60f
    [<Literal>]
    let MinConnectorOverlap = 20f<du>

/// The alphabets a variable is set in, indexed from the first letter of each.
module internal Alphabets =
    /// Math italic, a to z, in which variables are set.
    let italicSmall: Glyph array =
        [|
            Glyph(1296, 529f<du>, 454f<du>, -16f<du>, 0f<du>, 287f<du>); Glyph(1297, 429f<du>, 704f<du>, -16f<du>, 14f<du>, 165f<du>)
            Glyph(1298, 433f<du>, 454f<du>, -16f<du>, 25f<du>, 317f<du>); Glyph(1299, 520f<du>, 704f<du>, -16f<du>, 24f<du>, 442f<du>)
            Glyph(1300, 466f<du>, 454f<du>, -16f<du>, 0f<du>, 300f<du>); Glyph(1301, 490f<du>, 704f<du>, -204f<du>, 90f<du>, 464f<du>)
            Glyph(1302, 477f<du>, 454f<du>, -204f<du>, 25f<du>, 316f<du>); Glyph(1303, 576f<du>, 704f<du>, -16f<du>, 0f<du>, 213f<du>)
            Glyph(1304, 345f<du>, 672f<du>, -16f<du>, 0f<du>, 247f<du>); Glyph(1305, 412f<du>, 672f<du>, -204f<du>, 13f<du>, 359f<du>)
            Glyph(1306, 521f<du>, 704f<du>, -16f<du>, 15f<du>, 213f<du>); Glyph(1307, 298f<du>, 704f<du>, -16f<du>, 0f<du>, 184f<du>)
            Glyph(1308, 878f<du>, 454f<du>, -16f<du>, 0f<du>, 404f<du>); Glyph(1309, 600f<du>, 454f<du>, -16f<du>, 0f<du>, 265f<du>)
            Glyph(1310, 485f<du>, 454f<du>, -16f<du>, 12f<du>, 315f<du>); Glyph(1311, 503f<du>, 454f<du>, -204f<du>, 15f<du>, 246f<du>)
            Glyph(1312, 446f<du>, 454f<du>, -204f<du>, 34f<du>, 349f<du>); Glyph(1313, 451f<du>, 454f<du>, -16f<du>, 13f<du>, 247f<du>)
            Glyph(1314, 469f<du>, 454f<du>, -16f<du>, 0f<du>, 296f<du>); Glyph(1315, 361f<du>, 625f<du>, -16f<du>, 0f<du>, 225f<du>)
            Glyph(1316, 572f<du>, 454f<du>, -16f<du>, 0f<du>, 305f<du>); Glyph(1317, 485f<du>, 454f<du>, -16f<du>, 11f<du>, 294f<du>)
            Glyph(1318, 716f<du>, 454f<du>, -16f<du>, 3f<du>, 405f<du>); Glyph(1319, 572f<du>, 454f<du>, -16f<du>, 0f<du>, 329f<du>)
            Glyph(1320, 490f<du>, 454f<du>, -204f<du>, 28f<du>, 304f<du>); Glyph(1321, 465f<du>, 454f<du>, -16f<du>, 30f<du>, 336f<du>)
        |]
    /// Math italic, A to Z.
    let italicCapital: Glyph array =
        [|
            Glyph(1270, 750f<du>, 719f<du>, 0f<du>, 0f<du>, 550f<du>); Glyph(1271, 759f<du>, 688f<du>, 0f<du>, 25f<du>, 420f<du>)
            Glyph(1272, 715f<du>, 704f<du>, -32f<du>, 73f<du>, 596f<du>); Glyph(1273, 828f<du>, 688f<du>, 0f<du>, 4f<du>, 427f<du>)
            Glyph(1274, 738f<du>, 688f<du>, 0f<du>, 54f<du>, 483f<du>); Glyph(1275, 643f<du>, 688f<du>, 0f<du>, 134f<du>, 475f<du>)
            Glyph(1276, 786f<du>, 704f<du>, -32f<du>, 0f<du>, 596f<du>); Glyph(1277, 831f<du>, 688f<du>, 0f<du>, 78f<du>, 542f<du>)
            Glyph(1278, 440f<du>, 688f<du>, 0f<du>, 85f<du>, 347f<du>); Glyph(1279, 555f<du>, 688f<du>, -32f<du>, 106f<du>, 487f<du>)
            Glyph(1280, 849f<du>, 688f<du>, 0f<du>, 68f<du>, 545f<du>); Glyph(1281, 681f<du>, 688f<du>, 0f<du>, 0f<du>, 360f<du>)
            Glyph(1282, 970f<du>, 688f<du>, 0f<du>, 102f<du>, 625f<du>); Glyph(1283, 803f<du>, 688f<du>, 0f<du>, 106f<du>, 542f<du>)
            Glyph(1284, 763f<du>, 704f<du>, -32f<du>, 5f<du>, 495f<du>); Glyph(1285, 642f<du>, 688f<du>, 0f<du>, 140f<du>, 416f<du>)
            Glyph(1286, 791f<du>, 704f<du>, -204f<du>, 0f<du>, 495f<du>); Glyph(1287, 759f<du>, 688f<du>, -32f<du>, 24f<du>, 398f<du>)
            Glyph(1288, 613f<du>, 704f<du>, -32f<du>, 60f<du>, 498f<du>); Glyph(1289, 584f<du>, 688f<du>, 0f<du>, 148f<du>, 398f<du>)
            Glyph(1290, 683f<du>, 688f<du>, -32f<du>, 105f<du>, 421f<du>); Glyph(1291, 583f<du>, 688f<du>, -32f<du>, 214f<du>, 413f<du>)
            Glyph(1292, 944f<du>, 688f<du>, -32f<du>, 132f<du>, 552f<du>); Glyph(1293, 828f<du>, 688f<du>, 0f<du>, 51f<du>, 528f<du>)
            Glyph(1294, 581f<du>, 688f<du>, 0f<du>, 209f<du>, 399f<du>); Glyph(1295, 683f<du>, 688f<du>, 0f<du>, 68f<du>, 485f<du>)
        |]
    /// Math italic, alpha to omega.
    let italicGreek: Glyph array =
        [|
            Glyph(4459, 640f<du>, 454f<du>, -16f<du>, 0f<du>, 392f<du>); Glyph(4460, 566f<du>, 719f<du>, -204f<du>, 36f<du>, 437f<du>)
            Glyph(4461, 518f<du>, 454f<du>, -219f<du>, 53f<du>, 259f<du>); Glyph(4462, 444f<du>, 719f<du>, -16f<du>, 36f<du>, 335f<du>)
            Glyph(4483, 466f<du>, 454f<du>, -32f<du>, 0f<du>, 284f<du>); Glyph(4464, 438f<du>, 704f<du>, -204f<du>, 64f<du>, 313f<du>)
            Glyph(4465, 497f<du>, 454f<du>, -219f<du>, 27f<du>, 272f<du>); Glyph(4466, 469f<du>, 704f<du>, -16f<du>, 14f<du>, 310f<du>)
            Glyph(4467, 354f<du>, 454f<du>, -16f<du>, 0f<du>, 184f<du>); Glyph(4468, 576f<du>, 454f<du>, -16f<du>, 0f<du>, 331f<du>)
            Glyph(4470, 583f<du>, 704f<du>, -16f<du>, 0f<du>, 238f<du>); Glyph(4471, 603f<du>, 454f<du>, -219f<du>, 0f<du>, 349f<du>)
            Glyph(4472, 494f<du>, 454f<du>, 0f<du>, 58f<du>, 297f<du>); Glyph(4473, 438f<du>, 704f<du>, -204f<du>, 36f<du>, 285f<du>)
            Glyph(4583, 485f<du>, 454f<du>, -16f<du>, 12f<du>, 243f<du>); Glyph(4474, 570f<du>, 438f<du>, -16f<du>, 25f<du>, 328f<du>)
            Glyph(4475, 517f<du>, 454f<du>, -219f<du>, 13f<du>, 354f<du>); Glyph(4487, 363f<du>, 454f<du>, -110f<du>, 74f<du>, 182f<du>)
            Glyph(4476, 571f<du>, 438f<du>, -16f<du>, 24f<du>, 286f<du>); Glyph(4477, 437f<du>, 438f<du>, -16f<du>, 102f<du>, 269f<du>)
            Glyph(4478, 540f<du>, 454f<du>, -16f<du>, 12f<du>, 306f<du>); Glyph(4488, 654f<du>, 454f<du>, -219f<du>, 0f<du>, 355f<du>)
            Glyph(4480, 626f<du>, 454f<du>, -204f<du>, 0f<du>, 331f<du>); Glyph(4481, 651f<du>, 704f<du>, -204f<du>, 12f<du>, 469f<du>)
            Glyph(4482, 622f<du>, 454f<du>, -16f<du>, 10f<du>, 345f<du>)
        |]
    /// Math bold italic, a to z.
    let boldSmall: Glyph array =
        [|
            Glyph(1650, 633f<du>, 454f<du>, -16f<du>, 0f<du>, 336f<du>); Glyph(1651, 521f<du>, 704f<du>, -16f<du>, 13f<du>, 225f<du>)
            Glyph(1652, 513f<du>, 454f<du>, -16f<du>, 26f<du>, 365f<du>); Glyph(1653, 610f<du>, 704f<du>, -16f<du>, 22f<du>, 512f<du>)
            Glyph(1654, 554f<du>, 454f<du>, -16f<du>, 0f<du>, 340f<du>); Glyph(1655, 568f<du>, 704f<du>, -204f<du>, 86f<du>, 516f<du>)
            Glyph(1656, 545f<du>, 454f<du>, -204f<du>, 17f<du>, 339f<du>); Glyph(1657, 668f<du>, 704f<du>, -16f<du>, 0f<du>, 228f<du>)
            Glyph(1658, 405f<du>, 704f<du>, -16f<du>, 0f<du>, 282f<du>); Glyph(1659, 471f<du>, 704f<du>, -204f<du>, 7f<du>, 398f<du>)
            Glyph(1660, 604f<du>, 704f<du>, -16f<du>, 0f<du>, 228f<du>); Glyph(1661, 348f<du>, 704f<du>, -16f<du>, 0f<du>, 196f<du>)
            Glyph(1662, 1032f<du>, 454f<du>, -16f<du>, 0f<du>, 478f<du>); Glyph(1663, 713f<du>, 454f<du>, -16f<du>, 0f<du>, 318f<du>)
            Glyph(1664, 585f<du>, 454f<du>, -16f<du>, 12f<du>, 367f<du>); Glyph(1665, 601f<du>, 454f<du>, -204f<du>, 13f<du>, 296f<du>)
            Glyph(1666, 542f<du>, 454f<du>, -204f<du>, 29f<du>, 410f<du>); Glyph(1667, 529f<du>, 454f<du>, -16f<du>, 4f<du>, 282f<du>)
            Glyph(1668, 531f<du>, 454f<du>, -16f<du>, 0f<du>, 324f<du>); Glyph(1669, 415f<du>, 657f<du>, -16f<du>, 0f<du>, 254f<du>)
            Glyph(1670, 681f<du>, 454f<du>, -16f<du>, 0f<du>, 345f<du>); Glyph(1671, 567f<du>, 454f<du>, -16f<du>, 0f<du>, 332f<du>)
            Glyph(1672, 831f<du>, 454f<du>, -16f<du>, 0f<du>, 460f<du>); Glyph(1673, 659f<du>, 454f<du>, -16f<du>, 0f<du>, 359f<du>)
            Glyph(1674, 590f<du>, 454f<du>, -204f<du>, 20f<du>, 345f<du>); Glyph(1675, 555f<du>, 454f<du>, -16f<du>, 11f<du>, 379f<du>)
        |]
    /// Math bold italic, A to Z.
    let boldCapital: Glyph array =
        [|
            Glyph(1624, 869f<du>, 719f<du>, 0f<du>, 0f<du>, 608f<du>); Glyph(1625, 866f<du>, 688f<du>, 0f<du>, 16f<du>, 477f<du>)
            Glyph(1626, 817f<du>, 704f<du>, -16f<du>, 66f<du>, 658f<du>); Glyph(1627, 938f<du>, 688f<du>, 0f<du>, 5f<du>, 465f<du>)
            Glyph(1628, 810f<du>, 688f<du>, 0f<du>, 43f<du>, 515f<du>); Glyph(1629, 689f<du>, 688f<du>, 0f<du>, 148f<du>, 507f<du>)
            Glyph(1630, 887f<du>, 704f<du>, -16f<du>, 0f<du>, 658f<du>); Glyph(1631, 982f<du>, 688f<du>, 0f<du>, 73f<du>, 616f<du>)
            Glyph(1632, 511f<du>, 688f<du>, 0f<du>, 83f<du>, 383f<du>); Glyph(1633, 631f<du>, 688f<du>, -16f<du>, 91f<du>, 516f<du>)
            Glyph(1634, 971f<du>, 688f<du>, 0f<du>, 60f<du>, 604f<du>); Glyph(1635, 756f<du>, 688f<du>, 0f<du>, 0f<du>, 396f<du>)
            Glyph(1636, 1142f<du>, 688f<du>, 0f<du>, 102f<du>, 712f<du>); Glyph(1637, 950f<du>, 688f<du>, 0f<du>, 105f<du>, 616f<du>)
            Glyph(1638, 837f<du>, 704f<du>, -16f<du>, 6f<du>, 528f<du>); Glyph(1639, 723f<du>, 688f<du>, 0f<du>, 154f<du>, 468f<du>)
            Glyph(1640, 869f<du>, 704f<du>, -204f<du>, 0f<du>, 528f<du>); Glyph(1641, 872f<du>, 688f<du>, -16f<du>, 37f<du>, 457f<du>)
            Glyph(1642, 693f<du>, 704f<du>, -16f<du>, 49f<du>, 561f<du>); Glyph(1643, 637f<du>, 688f<du>, 0f<du>, 163f<du>, 434f<du>)
            Glyph(1644, 800f<du>, 688f<du>, -16f<du>, 105f<du>, 473f<du>); Glyph(1645, 678f<du>, 688f<du>, -16f<du>, 235f<du>, 476f<du>)
            Glyph(1646, 1093f<du>, 688f<du>, -16f<du>, 142f<du>, 637f<du>); Glyph(1647, 947f<du>, 688f<du>, 0f<du>, 34f<du>, 584f<du>)
            Glyph(1648, 675f<du>, 688f<du>, 0f<du>, 228f<du>, 460f<du>); Glyph(1649, 773f<du>, 688f<du>, 0f<du>, 60f<du>, 533f<du>)
        |]
    /// Upright a to z, in which function names are set.
    let uprightSmall: Glyph array =
        [|
            Glyph(66, 500f<du>, 454f<du>, -16f<du>, 11f<du>, 214f<du>); Glyph(67, 556f<du>, 704f<du>, -16f<du>, 0f<du>, 100f<du>)
            Glyph(68, 444f<du>, 454f<du>, -16f<du>, 0f<du>, 249f<du>); Glyph(69, 556f<du>, 704f<du>, -16f<du>, 0f<du>, 377f<du>)
            Glyph(70, 444f<du>, 454f<du>, -16f<du>, 0f<du>, 236f<du>); Glyph(71, 306f<du>, 704f<du>, 0f<du>, 79f<du>, 262f<du>)
            Glyph(72, 500f<du>, 454f<du>, -219f<du>, 13f<du>, 332f<du>); Glyph(73, 556f<du>, 704f<du>, 0f<du>, 7f<du>, 104f<du>)
            Glyph(74, 278f<du>, 657f<du>, 0f<du>, 0f<du>, 138f<du>); Glyph(75, 306f<du>, 657f<du>, -204f<du>, 0f<du>, 156f<du>)
            Glyph(76, 528f<du>, 704f<du>, 0f<du>, 11f<du>, 100f<du>); Glyph(77, 278f<du>, 704f<du>, 0f<du>, 5f<du>, 105f<du>)
            Glyph(78, 833f<du>, 454f<du>, 0f<du>, 8f<du>, 350f<du>); Glyph(79, 556f<du>, 454f<du>, 0f<du>, 7f<du>, 211f<du>)
            Glyph(80, 500f<du>, 454f<du>, -16f<du>, 0f<du>, 249f<du>); Glyph(81, 556f<du>, 454f<du>, -204f<du>, 0f<du>, 202f<du>)
            Glyph(82, 528f<du>, 454f<du>, -204f<du>, 27f<du>, 318f<du>); Glyph(83, 392f<du>, 454f<du>, 0f<du>, 0f<du>, 181f<du>)
            Glyph(84, 394f<du>, 454f<du>, -16f<du>, 0f<du>, 232f<du>); Glyph(85, 389f<du>, 625f<du>, -16f<du>, 0f<du>, 161f<du>)
            Glyph(86, 556f<du>, 454f<du>, -16f<du>, 7f<du>, 245f<du>); Glyph(87, 528f<du>, 438f<du>, -16f<du>, 8f<du>, 264f<du>)
            Glyph(88, 722f<du>, 438f<du>, -16f<du>, 9f<du>, 361f<du>); Glyph(89, 528f<du>, 438f<du>, 0f<du>, 16f<du>, 258f<du>)
            Glyph(90, 528f<du>, 438f<du>, -204f<du>, 8f<du>, 264f<du>); Glyph(91, 444f<du>, 438f<du>, 0f<du>, 0f<du>, 226f<du>)
        |]
    /// Upright A to Z.
    let uprightCapital: Glyph array =
        [|
            Glyph(34, 750f<du>, 719f<du>, 0f<du>, 0f<du>, 375f<du>); Glyph(35, 708f<du>, 688f<du>, 0f<du>, 0f<du>, 256f<du>)
            Glyph(36, 722f<du>, 704f<du>, -32f<du>, 0f<du>, 507f<du>); Glyph(37, 764f<du>, 688f<du>, 0f<du>, 0f<du>, 243f<du>)
            Glyph(38, 681f<du>, 688f<du>, 0f<du>, 0f<du>, 315f<du>); Glyph(39, 653f<du>, 688f<du>, 0f<du>, 0f<du>, 308f<du>)
            Glyph(40, 785f<du>, 704f<du>, -32f<du>, 0f<du>, 507f<du>); Glyph(41, 750f<du>, 688f<du>, 0f<du>, 0f<du>, 375f<du>)
            Glyph(42, 361f<du>, 688f<du>, 0f<du>, 0f<du>, 181f<du>); Glyph(43, 514f<du>, 688f<du>, -32f<du>, 0f<du>, 317f<du>)
            Glyph(44, 778f<du>, 688f<du>, 0f<du>, 0f<du>, 378f<du>); Glyph(45, 625f<du>, 688f<du>, 0f<du>, 0f<du>, 193f<du>)
            Glyph(46, 917f<du>, 688f<du>, 0f<du>, 0f<du>, 458f<du>); Glyph(47, 750f<du>, 688f<du>, 0f<du>, 0f<du>, 375f<du>)
            Glyph(48, 778f<du>, 704f<du>, -32f<du>, 0f<du>, 388f<du>); Glyph(49, 681f<du>, 688f<du>, 0f<du>, 0f<du>, 250f<du>)
            Glyph(50, 778f<du>, 704f<du>, -204f<du>, 0f<du>, 388f<du>); Glyph(51, 736f<du>, 688f<du>, -32f<du>, 24f<du>, 234f<du>)
            Glyph(52, 556f<du>, 704f<du>, -32f<du>, 0f<du>, 330f<du>); Glyph(53, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>)
            Glyph(54, 750f<du>, 688f<du>, -32f<du>, 0f<du>, 375f<du>); Glyph(55, 750f<du>, 688f<du>, -32f<du>, 8f<du>, 375f<du>)
            Glyph(56, 1028f<du>, 688f<du>, -32f<du>, 9f<du>, 514f<du>); Glyph(57, 750f<du>, 688f<du>, 0f<du>, 4f<du>, 361f<du>)
            Glyph(58, 750f<du>, 688f<du>, 0f<du>, 16f<du>, 375f<du>); Glyph(59, 611f<du>, 688f<du>, 0f<du>, 0f<du>, 317f<du>)
        |]
    /// Upright Alpha to Omega, as capital Greek is set.
    let uprightGreekCapital: Glyph array =
        [|
            Glyph(4113, 750f<du>, 719f<du>, 0f<du>, 0f<du>, 374f<du>); Glyph(4114, 708f<du>, 688f<du>, 0f<du>, 0f<du>, 286f<du>)
            Glyph(4101, 625f<du>, 688f<du>, 0f<du>, 0f<du>, 297f<du>); Glyph(4100, 833f<du>, 719f<du>, 0f<du>, 0f<du>, 416f<du>)
            Glyph(4115, 681f<du>, 688f<du>, 0f<du>, 0f<du>, 318f<du>); Glyph(4116, 611f<du>, 688f<du>, 0f<du>, 0f<du>, 316f<du>)
            Glyph(4117, 750f<du>, 688f<du>, 0f<du>, 0f<du>, 375f<du>); Glyph(4108, 778f<du>, 704f<du>, -32f<du>, 0f<du>, 389f<du>)
            Glyph(4118, 361f<du>, 688f<du>, 0f<du>, 0f<du>, 181f<du>); Glyph(4119, 778f<du>, 688f<du>, 0f<du>, 0f<du>, 378f<du>)
            Glyph(4102, 694f<du>, 719f<du>, 0f<du>, 0f<du>, 347f<du>); Glyph(4120, 917f<du>, 688f<du>, 0f<du>, 0f<du>, 458f<du>)
            Glyph(4121, 750f<du>, 688f<du>, 0f<du>, 0f<du>, 375f<du>); Glyph(4110, 667f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)
            Glyph(4122, 778f<du>, 704f<du>, -32f<du>, 0f<du>, 389f<du>); Glyph(4105, 750f<du>, 688f<du>, 0f<du>, 0f<du>, 375f<du>)
            Glyph(4123, 681f<du>, 688f<du>, 0f<du>, 0f<du>, 283f<du>); Glyph(0, 0f<du>, 0f<du>, 0f<du>, 0f<du>, 0f<du>)
            Glyph(4107, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 350f<du>); Glyph(4124, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>)
            Glyph(4109, 778f<du>, 704f<du>, 0f<du>, 0f<du>, 389f<du>); Glyph(4104, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 358f<du>)
            Glyph(4125, 750f<du>, 688f<du>, 0f<du>, 4f<du>, 361f<du>); Glyph(4106, 778f<du>, 688f<du>, 0f<du>, 0f<du>, 386f<du>)
            Glyph(4103, 722f<du>, 704f<du>, 0f<du>, 0f<du>, 360f<du>)
        |]
    /// Upright alpha to omega, as \mathrm sets small Greek.
    let uprightGreekSmall: Glyph array =
        [|
            Glyph(4178, 641f<du>, 454f<du>, -16f<du>, 24f<du>, 356f<du>); Glyph(4179, 558f<du>, 719f<du>, -204f<du>, 0f<du>, 280f<du>)
            Glyph(4180, 586f<du>, 454f<du>, -219f<du>, 0f<du>, 293f<du>); Glyph(4181, 474f<du>, 719f<du>, -16f<du>, 0f<du>, 232f<du>)
            Glyph(4202, 535f<du>, 454f<du>, -32f<du>, 0f<du>, 244f<du>); Glyph(4183, 530f<du>, 704f<du>, -204f<du>, 0f<du>, 224f<du>)
            Glyph(4184, 530f<du>, 454f<du>, -219f<du>, 0f<du>, 218f<du>); Glyph(4185, 488f<du>, 704f<du>, -16f<du>, 0f<du>, 247f<du>)
            Glyph(4186, 308f<du>, 454f<du>, -16f<du>, 24f<du>, 98f<du>); Glyph(4187, 530f<du>, 454f<du>, -16f<du>, 23f<du>, 247f<du>)
            Glyph(4189, 537f<du>, 704f<du>, -16f<du>, 54f<du>, 86f<du>); Glyph(4190, 530f<du>, 454f<du>, -219f<du>, 23f<du>, 237f<du>)
            Glyph(4191, 502f<du>, 454f<du>, 0f<du>, 0f<du>, 209f<du>); Glyph(4192, 530f<du>, 704f<du>, -204f<du>, 0f<du>, 196f<du>)
            Glyph(4271, 500f<du>, 454f<du>, -16f<du>, 0f<du>, 250f<du>); Glyph(4193, 586f<du>, 438f<du>, -16f<du>, 0f<du>, 279f<du>)
            Glyph(4194, 488f<du>, 454f<du>, -219f<du>, 0f<du>, 243f<du>); Glyph(4206, 474f<du>, 454f<du>, -110f<du>, 0f<du>, 237f<du>)
            Glyph(4195, 599f<du>, 438f<du>, -16f<du>, 0f<du>, 300f<du>); Glyph(4196, 530f<du>, 438f<du>, -16f<du>, 0f<du>, 232f<du>)
            Glyph(4197, 530f<du>, 454f<du>, -16f<du>, 0f<du>, 251f<du>); Glyph(4207, 641f<du>, 454f<du>, -219f<du>, 0f<du>, 302f<du>)
            Glyph(4199, 641f<du>, 454f<du>, -204f<du>, 24f<du>, 267f<du>); Glyph(4200, 641f<du>, 704f<du>, -204f<du>, 0f<du>, 348f<du>)
            Glyph(4201, 641f<du>, 454f<du>, -16f<du>, 0f<du>, 322f<du>)
        |]
    /// Upright 0 to 9.
    let digits: Glyph array =
        [|
            Glyph(17, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 254f<du>); Glyph(18, 500f<du>, 672f<du>, 0f<du>, 0f<du>, 257f<du>)
            Glyph(19, 500f<du>, 672f<du>, 0f<du>, 0f<du>, 240f<du>); Glyph(20, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 258f<du>)
            Glyph(21, 500f<du>, 688f<du>, 0f<du>, 0f<du>, 353f<du>); Glyph(22, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 256f<du>)
            Glyph(23, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 318f<du>); Glyph(24, 500f<du>, 688f<du>, -32f<du>, 13f<du>, 103f<du>)
            Glyph(25, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 261f<du>); Glyph(26, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 242f<du>)
        |]
    /// The italic shapes Unicode keeps outside the alphabets.
    let italicShapes: CG array =
        [|
            CG(8706, Glyph(4489, 531f<du>, 719f<du>, -32f<du>, 63f<du>, 361f<du>)); CG(1013, Glyph(4463, 406f<du>, 438f<du>, -16f<du>, 0f<du>, 269f<du>))
            CG(977, Glyph(4484, 591f<du>, 704f<du>, -16f<du>, 0f<du>, 411f<du>)); CG(1008, Glyph(4469, 624f<du>, 454f<du>, -16f<du>, 0f<du>, 365f<du>))
            CG(981, Glyph(4479, 596f<du>, 704f<du>, -204f<du>, 5f<du>, 423f<du>)); CG(1009, Glyph(4486, 517f<du>, 454f<du>, -204f<du>, 13f<du>, 361f<du>))
            CG(982, Glyph(4485, 828f<du>, 438f<du>, -16f<du>, 17f<du>, 453f<du>))
        |]
    /// Blackboard bold A to Z, which the second face is carried for.
    let blackboardCapital: Glyph array =
        [|
            Glyph(Face.Blackboard, 1, 722f<du>, 704f<du>, 0f<du>, 0f<du>, 361f<du>); Glyph(Face.Blackboard, 2, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)
            Glyph(Face.Blackboard, 3, 722f<du>, 704f<du>, -32f<du>, 0f<du>, 361f<du>); Glyph(Face.Blackboard, 4, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>)
            Glyph(Face.Blackboard, 5, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>); Glyph(Face.Blackboard, 6, 611f<du>, 688f<du>, 0f<du>, 0f<du>, 305f<du>)
            Glyph(Face.Blackboard, 7, 777f<du>, 704f<du>, -32f<du>, 0f<du>, 388f<du>); Glyph(Face.Blackboard, 8, 777f<du>, 688f<du>, 0f<du>, 0f<du>, 388f<du>)
            Glyph(Face.Blackboard, 9, 388f<du>, 688f<du>, 0f<du>, 0f<du>, 194f<du>); Glyph(Face.Blackboard, 10, 500f<du>, 688f<du>, -79f<du>, 0f<du>, 250f<du>)
            Glyph(Face.Blackboard, 11, 777f<du>, 688f<du>, 0f<du>, 0f<du>, 388f<du>); Glyph(Face.Blackboard, 12, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)
            Glyph(Face.Blackboard, 13, 944f<du>, 688f<du>, 0f<du>, 0f<du>, 472f<du>); Glyph(Face.Blackboard, 14, 722f<du>, 688f<du>, -32f<du>, 0f<du>, 361f<du>)
            Glyph(Face.Blackboard, 15, 777f<du>, 704f<du>, -32f<du>, 0f<du>, 388f<du>); Glyph(Face.Blackboard, 16, 611f<du>, 688f<du>, 0f<du>, 0f<du>, 305f<du>)
            Glyph(Face.Blackboard, 17, 777f<du>, 704f<du>, -188f<du>, 0f<du>, 388f<du>); Glyph(Face.Blackboard, 18, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>)
            Glyph(Face.Blackboard, 19, 555f<du>, 704f<du>, -16f<du>, 0f<du>, 277f<du>); Glyph(Face.Blackboard, 20, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)
            Glyph(Face.Blackboard, 21, 722f<du>, 688f<du>, -32f<du>, 0f<du>, 361f<du>); Glyph(Face.Blackboard, 22, 722f<du>, 688f<du>, -32f<du>, 0f<du>, 361f<du>)
            Glyph(Face.Blackboard, 23, 1000f<du>, 688f<du>, -32f<du>, 0f<du>, 500f<du>); Glyph(Face.Blackboard, 24, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>)
            Glyph(Face.Blackboard, 25, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>); Glyph(Face.Blackboard, 26, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)
        |]

/// Every character a formula may hold that no alphabet covers, ascending by codepoint.
module internal Repertoire =
    let all: CG array =
        [|
            CG(32, Glyph(1, 332f<du>, 0f<du>, 0f<du>, 0f<du>, 166f<du>)); CG(33, Glyph(2, 278f<du>, 719f<du>, 0f<du>, 0f<du>, 139f<du>))
            CG(34, Glyph(3, 374f<du>, 704f<du>, 421f<du>, 0f<du>, 187f<du>)); CG(35, Glyph(4, 833f<du>, 704f<du>, -204f<du>, 0f<du>, 416f<du>))
            CG(36, Glyph(5, 500f<du>, 750f<du>, -63f<du>, 0f<du>, 250f<du>)); CG(37, Glyph(6, 833f<du>, 750f<du>, -63f<du>, 0f<du>, 416f<du>))
            CG(38, Glyph(7, 778f<du>, 719f<du>, -32f<du>, 0f<du>, 389f<du>)); CG(39, Glyph(103, 278f<du>, 704f<du>, 421f<du>, 0f<du>, 139f<du>))
            CG(40, Glyph(9, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>)); CG(41, Glyph(10, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>))
            CG(42, Glyph(11, 500f<du>, 750f<du>, 312f<du>, 0f<du>, 398f<du>)); CG(43, Glyph(12, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>))
            CG(44, Glyph(13, 278f<du>, 110f<du>, -204f<du>, 0f<du>, 139f<du>)); CG(45, Glyph(14, 333f<du>, 250f<du>, 187f<du>, 0f<du>, 166f<du>))
            CG(46, Glyph(15, 278f<du>, 110f<du>, 0f<du>, 0f<du>, 139f<du>)); CG(47, Glyph(16, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>))
            CG(58, Glyph(27, 278f<du>, 438f<du>, 0f<du>, 0f<du>, 139f<du>)); CG(59, Glyph(28, 278f<du>, 438f<du>, -204f<du>, 0f<du>, 139f<du>))
            CG(60, Glyph(29, 778f<du>, 547f<du>, -47f<du>, 0f<du>, 389f<du>)); CG(61, Glyph(30, 778f<du>, 375f<du>, 125f<du>, 0f<du>, 389f<du>))
            CG(62, Glyph(31, 778f<du>, 547f<du>, -47f<du>, 0f<du>, 389f<du>)); CG(63, Glyph(32, 472f<du>, 704f<du>, 0f<du>, 0f<du>, 236f<du>))
            CG(64, Glyph(33, 778f<du>, 704f<du>, -16f<du>, 0f<du>, 389f<du>)); CG(91, Glyph(60, 278f<du>, 750f<du>, -250f<du>, 6f<du>, 139f<du>))
            CG(92, Glyph(61, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>)); CG(93, Glyph(62, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>))
            CG(94, Glyph(63, 556f<du>, 750f<du>, 562f<du>, 33f<du>, 278f<du>)); CG(95, Glyph(64, 333f<du>, -93f<du>, -141f<du>, 28f<du>, 166f<du>))
            CG(96, Glyph(122, 500f<du>, 704f<du>, 500f<du>, 0f<du>, 219f<du>)); CG(123, Glyph(92, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>))
            CG(124, Glyph(93, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>)); CG(125, Glyph(94, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>))
            CG(126, Glyph(95, 556f<du>, 313f<du>, 187f<du>, 27f<du>, 278f<du>)); CG(163, Glyph(98, 750f<du>, 688f<du>, -47f<du>, 0f<du>, 375f<du>))
            CG(172, Glyph(2734, 667f<du>, 375f<du>, 125f<du>, 0f<du>, 333f<du>)); CG(176, Glyph(175, 375f<du>, 688f<du>, 406f<du>, 0f<du>, 187f<du>))
            CG(177, Glyph(2619, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>)); CG(181, Glyph(203, 556f<du>, 454f<du>, -204f<du>, 6f<du>, 278f<du>))
            CG(215, Glyph(2638, 778f<du>, 500f<du>, 0f<du>, 0f<du>, 389f<du>)); CG(247, Glyph(2623, 778f<du>, 516f<du>, -16f<du>, 0f<du>, 389f<du>))
            CG(8211, Glyph(110, 500f<du>, 282f<du>, 250f<du>, 27f<du>, 250f<du>)); CG(8224, Glyph(111, 444f<du>, 704f<du>, -219f<du>, 0f<du>, 222f<du>))
            CG(8225, Glyph(112, 444f<du>, 704f<du>, -204f<du>, 0f<du>, 222f<du>)); CG(8226, Glyph(114, 500f<du>, 454f<du>, 46f<du>, 0f<du>, 250f<du>))
            CG(8230, Glyph(119, 837f<du>, 110f<du>, 0f<du>, 0f<du>, 418f<du>)); CG(8240, Glyph(120, 1140f<du>, 750f<du>, -63f<du>, 0f<du>, 570f<du>))
            CG(8242, Glyph(2974, 311f<du>, 750f<du>, 421f<du>, 0f<du>, 155f<du>)); CG(8243, Glyph(2976, 511f<du>, 750f<du>, 421f<du>, 0f<du>, 255f<du>))
            CG(8450, Glyph(3495, 667f<du>, 704f<du>, -32f<du>, 0f<du>, 335f<du>)); CG(8461, Glyph(3500, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>))
            CG(8467, Glyph(1263, 417f<du>, 704f<du>, -16f<du>, 9f<du>, 208f<du>)); CG(8469, Glyph(3506, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>))
            CG(8473, Glyph(3508, 639f<du>, 688f<du>, 0f<du>, 0f<du>, 247f<du>)); CG(8474, Glyph(3509, 667f<du>, 704f<du>, -204f<du>, 0f<du>, 333f<du>))
            CG(8477, Glyph(3510, 639f<du>, 688f<du>, 0f<du>, 0f<du>, 247f<du>)); CG(8484, Glyph(3518, 667f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>))
            CG(8592, Glyph(1857, 1000f<du>, 516f<du>, -16f<du>, 0f<du>, 500f<du>)); CG(8593, Glyph(1867, 500f<du>, 688f<du>, -204f<du>, 0f<du>, 250f<du>))
            CG(8594, Glyph(1858, 1000f<du>, 516f<du>, -16f<du>, 0f<du>, 500f<du>)); CG(8595, Glyph(1868, 500f<du>, 704f<du>, -188f<du>, 0f<du>, 250f<du>))
            CG(8596, Glyph(1889, 1000f<du>, 516f<du>, -16f<du>, 0f<du>, 500f<du>)); CG(8614, Glyph(1944, 977f<du>, 516f<du>, -16f<du>, 0f<du>, 488f<du>))
            CG(8635, Glyph(1997, 771f<du>, 688f<du>, -63f<du>, 0f<du>, 385f<du>)); CG(8656, Glyph(2099, 1000f<du>, 532f<du>, -32f<du>, 0f<du>, 500f<du>))
            CG(8658, Glyph(2100, 1000f<du>, 532f<du>, -32f<du>, 0f<du>, 500f<du>)); CG(8660, Glyph(2119, 1000f<du>, 532f<du>, -32f<du>, 0f<du>, 500f<du>))
            CG(8704, Glyph(2782, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)); CG(8706, Glyph(4208, 586f<du>, 719f<du>, -32f<du>, 0f<du>, 291f<du>))
            CG(8707, Glyph(2784, 556f<du>, 688f<du>, 0f<du>, 0f<du>, 278f<du>)); CG(8709, Glyph(2786, 500f<du>, 782f<du>, -79f<du>, 0f<du>, 250f<du>))
            CG(8710, Glyph(4274, 833f<du>, 719f<du>, 0f<du>, 0f<du>, 416f<du>)); CG(8711, Glyph(4097, 833f<du>, 688f<du>, -32f<du>, 0f<du>, 416f<du>))
            CG(8712, Glyph(2926, 667f<du>, 547f<du>, -47f<du>, 0f<du>, 333f<du>)); CG(8713, Glyph(2928, 667f<du>, 735f<du>, -235f<du>, 0f<du>, 333f<du>))
            CG(8715, Glyph(2927, 667f<du>, 547f<du>, -47f<du>, 0f<du>, 333f<du>)); CG(8722, Glyph(2615, 778f<du>, 282f<du>, 218f<du>, 0f<du>, 389f<du>))
            CG(8723, Glyph(2620, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>)); CG(8726, Glyph(2669, 568f<du>, 610f<du>, -110f<du>, 0f<du>, 284f<du>))
            CG(8727, Glyph(2655, 500f<du>, 469f<du>, 31f<du>, 0f<du>, 250f<du>)); CG(8728, Glyph(2635, 412f<du>, 407f<du>, 93f<du>, 0f<du>, 206f<du>))
            CG(8733, Glyph(209, 778f<du>, 454f<du>, -16f<du>, 0f<du>, 389f<du>)); CG(8734, Glyph(152, 1000f<du>, 454f<du>, -16f<du>, 0f<du>, 500f<du>))
            CG(8736, Glyph(2662, 778f<du>, 735f<du>, 0f<du>, 0f<du>, 389f<du>)); CG(8739, Glyph(2670, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>))
            CG(8741, Glyph(2671, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>)); CG(8743, Glyph(2769, 667f<du>, 610f<du>, -32f<du>, 0f<du>, 333f<du>))
            CG(8744, Glyph(2770, 667f<du>, 610f<du>, -32f<du>, 0f<du>, 333f<du>)); CG(8745, Glyph(2763, 667f<du>, 610f<du>, -32f<du>, 0f<du>, 333f<du>))
            CG(8746, Glyph(2764, 667f<du>, 610f<du>, -32f<du>, 0f<du>, 333f<du>)); CG(8756, Glyph(2629, 516f<du>, 422f<du>, 78f<du>, 0f<du>, 258f<du>))
            CG(8757, Glyph(2630, 516f<du>, 422f<du>, 78f<du>, 0f<du>, 258f<du>)); CG(8764, Glyph(2941, 773f<du>, 375f<du>, 125f<du>, 0f<du>, 386f<du>))
            CG(8773, Glyph(2949, 778f<du>, 563f<du>, 31f<du>, 0f<du>, 389f<du>)); CG(8776, Glyph(2952, 773f<du>, 469f<du>, 31f<du>, 0f<du>, 386f<du>))
            CG(8800, Glyph(2824, 778f<du>, 735f<du>, -235f<du>, 0f<du>, 389f<du>)); CG(8801, Glyph(2825, 778f<du>, 469f<du>, 31f<du>, 0f<du>, 389f<du>))
            CG(8804, Glyph(2862, 778f<du>, 641f<du>, -125f<du>, 0f<du>, 389f<du>)); CG(8805, Glyph(2863, 778f<du>, 641f<du>, -125f<du>, 0f<du>, 389f<du>))
            CG(8810, Glyph(2886, 1000f<du>, 547f<du>, -47f<du>, 0f<du>, 500f<du>)); CG(8811, Glyph(2887, 1000f<du>, 547f<du>, -47f<du>, 0f<du>, 500f<du>))
            CG(8834, Glyph(2914, 778f<du>, 547f<du>, -47f<du>, 0f<du>, 389f<du>)); CG(8835, Glyph(2915, 778f<du>, 547f<du>, -47f<du>, 0f<du>, 389f<du>))
            CG(8838, Glyph(2918, 778f<du>, 641f<du>, -141f<du>, 0f<du>, 389f<du>)); CG(8839, Glyph(2919, 778f<du>, 641f<du>, -141f<du>, 0f<du>, 389f<du>))
            CG(8853, Glyph(2805, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>)); CG(8855, Glyph(2810, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>))
            CG(8869, Glyph(2741, 778f<du>, 688f<du>, 0f<du>, 0f<du>, 389f<du>)); CG(8901, Glyph(2625, 278f<du>, 313f<du>, 187f<du>, 0f<du>, 139f<du>))
            CG(8942, Glyph(2631, 218f<du>, 594f<du>, -94f<du>, 0f<du>, 109f<du>)); CG(8943, Glyph(2632, 776f<du>, 313f<du>, 187f<du>, 0f<du>, 388f<du>))
            CG(8945, Glyph(2634, 613f<du>, 500f<du>, 0f<du>, 0f<du>, 306f<du>)); CG(9633, Glyph(3003, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>))
            CG(9651, Glyph(3009, 968f<du>, 750f<du>, -16f<du>, 0f<du>, 484f<du>)); CG(10216, Glyph(2579, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>))
            CG(10217, Glyph(2580, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>)); CG(10229, Glyph(1859, 1463f<du>, 516f<du>, -16f<du>, 0f<du>, 731f<du>))
            CG(10230, Glyph(1860, 1463f<du>, 516f<du>, -16f<du>, 0f<du>, 731f<du>)); CG(10234, Glyph(2120, 1534f<du>, 532f<du>, -32f<du>, 0f<du>, 767f<du>))
        |]

/// Single glyphs the library refers to that no alphabet covers.
module Symbols =
    /// The upright d of a derivative, which is not a variable.
    let uprightD = Glyph(69, 556f<du>, 704f<du>, -16f<du>, 0f<du>, 377f<du>)

/// Operators whose codepoints are easy to mistake for the keys that resemble them.
module Operators =
    /// The plus sign.
    let plus = Glyph(12, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>)
    /// The minus sign, which is longer than the hyphen.
    let minus = Glyph(2615, 778f<du>, 282f<du>, 218f<du>, 0f<du>, 389f<du>)
    /// The multiplication cross.
    let times = Glyph(2638, 778f<du>, 500f<du>, 0f<du>, 0f<du>, 389f<du>)
    /// The division sign.
    let divide = Glyph(2623, 778f<du>, 516f<du>, -16f<du>, 0f<du>, 389f<du>)
    /// The equals sign.
    let equals = Glyph(30, 778f<du>, 375f<du>, 125f<du>, 0f<du>, 389f<du>)
    /// The centred dot of a product.
    let cdot = Glyph(2625, 278f<du>, 313f<du>, 187f<du>, 0f<du>, 139f<du>)

/// Accents, which are placed by the point they attach over.
module Accents =
    /// The circumflex of \hat.
    let hat = Glyph(2270, 0f<du>, 735f<du>, 578f<du>, 0f<du>, -264f<du>)
    /// The tilde of \tilde.
    let tilde = Glyph(2272, 0f<du>, 750f<du>, 546f<du>, 0f<du>, -264f<du>)
    /// The macron of \bar.
    let bar = Glyph(1789, 0f<du>, 641f<du>, 609f<du>, 0f<du>, -263f<du>)
    /// The right arrow of \vec.
    let vec = Glyph(1817, 0f<du>, 719f<du>, 515f<du>, 0f<du>, -264f<du>)
    /// The single dot of \dot, a first derivative in time.
    let dot = Glyph(1790, 0f<du>, 688f<du>, 562f<du>, 0f<du>, -265f<du>)
    /// The double dot of \ddot, a second derivative in time.
    let doubleDot = Glyph(1791, 0f<du>, 672f<du>, 578f<du>, 0f<du>, -261f<du>)
    /// The caron of \check.
    let check = Glyph(2268, 0f<du>, 735f<du>, 578f<du>, 0f<du>, -264f<du>)
    /// The acute of \acute.
    let acute = Glyph(1798, 0f<du>, 735f<du>, 546f<du>, 0f<du>, -233f<du>)
    /// The grave of \grave.
    let grave = Glyph(1797, 0f<du>, 735f<du>, 546f<du>, 0f<du>, -295f<du>)
    /// The breve of \breve.
    let breve = Glyph(2264, 0f<du>, 735f<du>, 593f<du>, 0f<du>, -264f<du>)

/// Delimiters, which grow to the height of what they hold.
module Delimiters =
    /// The opening round bracket.
    let roundLeft =
        StretchyGlyph(
            Glyph(9, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>),
            [|
                StretchSize(Glyph(9, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>), 997f<du>); StretchSize(Glyph(2367, 422f<du>, 797f<du>, -297f<du>, 0f<du>, 211f<du>), 1095f<du>)
                StretchSize(Glyph(2389, 458f<du>, 860f<du>, -360f<du>, 0f<du>, 229f<du>), 1195f<du>); StretchSize(Glyph(2411, 523f<du>, 985f<du>, -485f<du>, 0f<du>, 261f<du>), 1445f<du>)
                StretchSize(Glyph(2433, 597f<du>, 1157f<du>, -657f<du>, 0f<du>, 298f<du>), 1793f<du>); StretchSize(Glyph(2455, 663f<du>, 1297f<du>, -797f<du>, 0f<du>, 331f<du>), 2093f<du>)
                StretchSize(Glyph(2477, 736f<du>, 1454f<du>, -954f<du>, 0f<du>, 368f<du>), 2393f<du>); StretchSize(Glyph(2499, 875f<du>, 1750f<du>, -1250f<du>, 0f<du>, 437f<du>), 2991f<du>)
            |],
            [|
                AssemblyPart(Glyph(2503, 875f<du>, 1500f<du>, 0f<du>, 0f<du>, 437f<du>), 0f<du>, 249f<du>, 1495f<du>, false)
                AssemblyPart(Glyph(2504, 875f<du>, 500f<du>, 0f<du>, 0f<du>, 437f<du>), 498f<du>, 498f<du>, 498f<du>, true)
                AssemblyPart(Glyph(2505, 875f<du>, 1500f<du>, 0f<du>, 0f<du>, 437f<du>), 249f<du>, 0f<du>, 1495f<du>, false)
            |])
    /// The closing round bracket.
    let roundRight =
        StretchyGlyph(
            Glyph(10, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>),
            [|
                StretchSize(Glyph(10, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>), 997f<du>); StretchSize(Glyph(2368, 422f<du>, 797f<du>, -297f<du>, 0f<du>, 211f<du>), 1095f<du>)
                StretchSize(Glyph(2390, 458f<du>, 860f<du>, -360f<du>, 0f<du>, 229f<du>), 1195f<du>); StretchSize(Glyph(2412, 523f<du>, 985f<du>, -485f<du>, 0f<du>, 261f<du>), 1445f<du>)
                StretchSize(Glyph(2434, 597f<du>, 1157f<du>, -657f<du>, 0f<du>, 298f<du>), 1793f<du>); StretchSize(Glyph(2456, 663f<du>, 1297f<du>, -797f<du>, 0f<du>, 331f<du>), 2093f<du>)
                StretchSize(Glyph(2478, 736f<du>, 1454f<du>, -954f<du>, 0f<du>, 368f<du>), 2393f<du>); StretchSize(Glyph(2500, 875f<du>, 1750f<du>, -1250f<du>, 0f<du>, 437f<du>), 2991f<du>)
            |],
            [|
                AssemblyPart(Glyph(2506, 875f<du>, 1500f<du>, 0f<du>, 0f<du>, 437f<du>), 0f<du>, 249f<du>, 1495f<du>, false)
                AssemblyPart(Glyph(2507, 875f<du>, 500f<du>, 0f<du>, 0f<du>, 437f<du>), 498f<du>, 498f<du>, 498f<du>, true)
                AssemblyPart(Glyph(2508, 875f<du>, 1500f<du>, 0f<du>, 0f<du>, 437f<du>), 249f<du>, 0f<du>, 1495f<du>, false)
            |])
    /// The opening square bracket.
    let squareLeft =
        StretchyGlyph(
            Glyph(60, 278f<du>, 750f<du>, -250f<du>, 6f<du>, 139f<du>),
            [|
                StretchSize(Glyph(60, 278f<du>, 750f<du>, -250f<du>, 6f<du>, 139f<du>), 1001f<du>); StretchSize(Glyph(2373, 340f<du>, 813f<du>, -313f<du>, 0f<du>, 170f<du>), 1101f<du>)
                StretchSize(Glyph(2395, 417f<du>, 860f<du>, -360f<du>, 0f<du>, 208f<du>), 1201f<du>); StretchSize(Glyph(2417, 444f<du>, 985f<du>, -485f<du>, 0f<du>, 222f<du>), 1451f<du>)
                StretchSize(Glyph(2439, 472f<du>, 1157f<du>, -657f<du>, 4f<du>, 236f<du>), 1801f<du>); StretchSize(Glyph(2461, 499f<du>, 1313f<du>, -813f<du>, 7f<du>, 249f<du>), 2101f<du>)
                StretchSize(Glyph(2483, 528f<du>, 1454f<du>, -954f<du>, 9f<du>, 264f<du>), 2401f<du>); StretchSize(Glyph(2525, 667f<du>, 1750f<du>, -1250f<du>, 8f<du>, 333f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(2527, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 0f<du>, 500f<du>, 1500f<du>, false)
                AssemblyPart(Glyph(2528, 667f<du>, 1000f<du>, 0f<du>, 0f<du>, 333f<du>), 1000f<du>, 1000f<du>, 1000f<du>, true)
                AssemblyPart(Glyph(2529, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 500f<du>, 0f<du>, 1500f<du>, false)
            |])
    /// The closing square bracket.
    let squareRight =
        StretchyGlyph(
            Glyph(62, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>),
            [|
                StretchSize(Glyph(62, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>), 1001f<du>); StretchSize(Glyph(2374, 340f<du>, 813f<du>, -313f<du>, 0f<du>, 170f<du>), 1101f<du>)
                StretchSize(Glyph(2396, 417f<du>, 860f<du>, -360f<du>, 0f<du>, 208f<du>), 1201f<du>); StretchSize(Glyph(2418, 444f<du>, 985f<du>, -485f<du>, 0f<du>, 222f<du>), 1451f<du>)
                StretchSize(Glyph(2440, 472f<du>, 1157f<du>, -657f<du>, 0f<du>, 236f<du>), 1801f<du>); StretchSize(Glyph(2462, 499f<du>, 1313f<du>, -813f<du>, 0f<du>, 249f<du>), 2101f<du>)
                StretchSize(Glyph(2484, 528f<du>, 1454f<du>, -954f<du>, 0f<du>, 264f<du>), 2401f<du>); StretchSize(Glyph(2526, 667f<du>, 1750f<du>, -1250f<du>, 0f<du>, 333f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(2530, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 0f<du>, 500f<du>, 1500f<du>, false)
                AssemblyPart(Glyph(2531, 667f<du>, 1000f<du>, 0f<du>, 0f<du>, 333f<du>), 1000f<du>, 1000f<du>, 1000f<du>, true)
                AssemblyPart(Glyph(2532, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 500f<du>, 0f<du>, 1500f<du>, false)
            |])
    /// The opening curly bracket.
    let curlyLeft =
        StretchyGlyph(
            Glyph(92, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>),
            [|
                StretchSize(Glyph(92, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>), 1001f<du>); StretchSize(Glyph(2371, 540f<du>, 813f<du>, -313f<du>, 0f<du>, 270f<du>), 1101f<du>)
                StretchSize(Glyph(2393, 583f<du>, 860f<du>, -360f<du>, 0f<du>, 291f<du>), 1201f<du>); StretchSize(Glyph(2415, 624f<du>, 985f<du>, -485f<du>, 0f<du>, 312f<du>), 1451f<du>)
                StretchSize(Glyph(2437, 667f<du>, 1157f<du>, -657f<du>, 0f<du>, 333f<du>), 1801f<du>); StretchSize(Glyph(2459, 707f<du>, 1313f<du>, -813f<du>, 0f<du>, 353f<du>), 2101f<du>)
                StretchSize(Glyph(2481, 750f<du>, 1454f<du>, -954f<du>, 0f<du>, 375f<du>), 2401f<du>); StretchSize(Glyph(2515, 902f<du>, 1750f<du>, -1250f<du>, 0f<du>, 451f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(2517, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 0f<du>, 374f<du>, 750f<du>, false)
                AssemblyPart(Glyph(2518, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 748f<du>, 748f<du>, 748f<du>, true)
                AssemblyPart(Glyph(2519, 902f<du>, 1500f<du>, 0f<du>, 0f<du>, 451f<du>), 374f<du>, 374f<du>, 1500f<du>, false)
                AssemblyPart(Glyph(2518, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 748f<du>, 748f<du>, 748f<du>, true)
                AssemblyPart(Glyph(2520, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 374f<du>, 0f<du>, 750f<du>, false)
            |])
    /// The closing curly bracket.
    let curlyRight =
        StretchyGlyph(
            Glyph(94, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>),
            [|
                StretchSize(Glyph(94, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>), 1001f<du>); StretchSize(Glyph(2372, 540f<du>, 813f<du>, -313f<du>, 0f<du>, 270f<du>), 1101f<du>)
                StretchSize(Glyph(2394, 583f<du>, 860f<du>, -360f<du>, 0f<du>, 291f<du>), 1201f<du>); StretchSize(Glyph(2416, 624f<du>, 985f<du>, -485f<du>, 0f<du>, 312f<du>), 1451f<du>)
                StretchSize(Glyph(2438, 667f<du>, 1157f<du>, -657f<du>, 0f<du>, 333f<du>), 1801f<du>); StretchSize(Glyph(2460, 707f<du>, 1313f<du>, -813f<du>, 0f<du>, 353f<du>), 2101f<du>)
                StretchSize(Glyph(2482, 750f<du>, 1454f<du>, -954f<du>, 0f<du>, 375f<du>), 2401f<du>); StretchSize(Glyph(2516, 902f<du>, 1750f<du>, -1250f<du>, 0f<du>, 451f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(2521, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 0f<du>, 374f<du>, 750f<du>, false)
                AssemblyPart(Glyph(2522, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 748f<du>, 748f<du>, 748f<du>, true)
                AssemblyPart(Glyph(2523, 902f<du>, 1500f<du>, 0f<du>, 0f<du>, 451f<du>), 374f<du>, 374f<du>, 1500f<du>, false)
                AssemblyPart(Glyph(2522, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 748f<du>, 748f<du>, 748f<du>, true)
                AssemblyPart(Glyph(2524, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 374f<du>, 0f<du>, 750f<du>, false)
            |])
    /// The opening angle bracket, as a bra opens.
    let angleLeft =
        StretchyGlyph(
            Glyph(2579, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>),
            [|
                StretchSize(Glyph(2579, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>), 1001f<du>); StretchSize(Glyph(2583, 428f<du>, 813f<du>, -313f<du>, 0f<du>, 214f<du>), 1101f<du>)
                StretchSize(Glyph(2587, 472f<du>, 860f<du>, -360f<du>, 0f<du>, 236f<du>), 1201f<du>); StretchSize(Glyph(2591, 537f<du>, 985f<du>, -485f<du>, 0f<du>, 268f<du>), 1451f<du>)
                StretchSize(Glyph(2595, 611f<du>, 1157f<du>, -657f<du>, 0f<du>, 305f<du>), 1801f<du>); StretchSize(Glyph(2599, 677f<du>, 1313f<du>, -813f<du>, 0f<du>, 338f<du>), 2101f<du>)
                StretchSize(Glyph(2603, 750f<du>, 1454f<du>, -954f<du>, 0f<du>, 375f<du>), 2401f<du>); StretchSize(Glyph(2607, 908f<du>, 1750f<du>, -1250f<du>, 0f<du>, 454f<du>), 3001f<du>)
            |],
            [||])
    /// The closing angle bracket, as a ket closes.
    let angleRight =
        StretchyGlyph(
            Glyph(2580, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>),
            [|
                StretchSize(Glyph(2580, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>), 1001f<du>); StretchSize(Glyph(2584, 428f<du>, 813f<du>, -313f<du>, 0f<du>, 214f<du>), 1101f<du>)
                StretchSize(Glyph(2588, 472f<du>, 860f<du>, -360f<du>, 0f<du>, 236f<du>), 1201f<du>); StretchSize(Glyph(2592, 537f<du>, 985f<du>, -485f<du>, 0f<du>, 268f<du>), 1451f<du>)
                StretchSize(Glyph(2596, 611f<du>, 1157f<du>, -657f<du>, 0f<du>, 305f<du>), 1801f<du>); StretchSize(Glyph(2600, 677f<du>, 1313f<du>, -813f<du>, 0f<du>, 338f<du>), 2101f<du>)
                StretchSize(Glyph(2604, 750f<du>, 1454f<du>, -954f<du>, 0f<du>, 375f<du>), 2401f<du>); StretchSize(Glyph(2608, 908f<du>, 1750f<du>, -1250f<du>, 0f<du>, 454f<du>), 3001f<du>)
            |],
            [||])
    /// The vertical bar of an absolute value, used on both sides.
    let bar =
        StretchyGlyph(
            Glyph(93, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>),
            [|
                StretchSize(Glyph(93, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>), 1001f<du>); StretchSize(Glyph(2677, 278f<du>, 860f<du>, -360f<du>, 0f<du>, 139f<du>), 1203f<du>)
                StretchSize(Glyph(2684, 278f<du>, 985f<du>, -485f<du>, 0f<du>, 139f<du>), 1445f<du>); StretchSize(Glyph(2691, 278f<du>, 1125f<du>, -625f<du>, 0f<du>, 139f<du>), 1735f<du>)
                StretchSize(Glyph(2698, 278f<du>, 1297f<du>, -797f<du>, 0f<du>, 139f<du>), 2085f<du>); StretchSize(Glyph(2705, 278f<du>, 1500f<du>, -1000f<du>, 0f<du>, 139f<du>), 2503f<du>)
                StretchSize(Glyph(2712, 278f<du>, 1766f<du>, -1266f<du>, 0f<du>, 139f<du>), 3005f<du>); StretchSize(Glyph(2719, 278f<du>, 2063f<du>, -1563f<du>, 0f<du>, 139f<du>), 3607f<du>)
            |],
            [|
                AssemblyPart(Glyph(2721, 278f<du>, 1204f<du>, 0f<du>, 0f<du>, 139f<du>), 0f<du>, 601f<du>, 1202f<du>, false)
                AssemblyPart(Glyph(2722, 278f<du>, 1204f<du>, 0f<du>, 0f<du>, 139f<du>), 1202f<du>, 1202f<du>, 1202f<du>, true)
                AssemblyPart(Glyph(2723, 278f<du>, 1204f<du>, 0f<du>, 0f<du>, 139f<du>), 601f<du>, 0f<du>, 1202f<du>, false)
            |])

/// Large operators, which take a taller glyph in display style and may carry limits.
module BigOperators =
    /// The summation sign.
    let sum =
        StretchyGlyph(
            Glyph(3060, 1056f<du>, 750f<du>, -250f<du>, 0f<du>, 528f<du>),
            [|
                StretchSize(Glyph(3060, 1056f<du>, 750f<du>, -250f<du>, 0f<du>, 528f<du>), 1001f<du>); StretchSize(Glyph(3074, 1444f<du>, 954f<du>, -454f<du>, 0f<du>, 722f<du>), 1401f<du>)
            |],
            [||])
    /// The product sign.
    let product =
        StretchyGlyph(
            Glyph(3061, 944f<du>, 750f<du>, -250f<du>, 0f<du>, 472f<du>),
            [|
                StretchSize(Glyph(3061, 944f<du>, 750f<du>, -250f<du>, 0f<du>, 472f<du>), 1001f<du>); StretchSize(Glyph(3075, 1278f<du>, 954f<du>, -454f<du>, 0f<du>, 639f<du>), 1401f<du>)
            |],
            [||])
    /// The coproduct sign.
    let coproduct =
        StretchyGlyph(
            Glyph(3062, 944f<du>, 750f<du>, -250f<du>, 0f<du>, 472f<du>),
            [|
                StretchSize(Glyph(3062, 944f<du>, 750f<du>, -250f<du>, 0f<du>, 472f<du>), 1001f<du>); StretchSize(Glyph(3076, 1278f<du>, 954f<du>, -454f<du>, 0f<du>, 639f<du>), 1401f<du>)
            |],
            [||])
    /// The integral sign.
    let integral =
        StretchyGlyph(
            Glyph(3049, 665f<du>, 813f<du>, -313f<du>, 332f<du>, 332f<du>),
            [|
                StretchSize(Glyph(3049, 665f<du>, 813f<du>, -313f<du>, 332f<du>, 332f<du>), 1112f<du>); StretchSize(Glyph(3063, 999f<du>, 1360f<du>, -860f<du>, 591f<du>, 499f<du>), 2223f<du>)
            |],
            [||])
    /// The contour integral sign.
    let contourIntegral =
        StretchyGlyph(
            Glyph(3053, 665f<du>, 813f<du>, -313f<du>, 332f<du>, 332f<du>),
            [|
                StretchSize(Glyph(3053, 665f<du>, 813f<du>, -313f<du>, 332f<du>, 332f<du>), 1112f<du>); StretchSize(Glyph(3067, 999f<du>, 1360f<du>, -860f<du>, 591f<du>, 499f<du>), 2223f<du>)
            |],
            [||])
    /// The n-ary union sign.
    let union =
        StretchyGlyph(
            Glyph(2767, 833f<du>, 750f<du>, -282f<du>, 0f<du>, 416f<du>),
            [|
                StretchSize(Glyph(2767, 833f<du>, 750f<du>, -282f<du>, 0f<du>, 416f<du>), 1023f<du>); StretchSize(Glyph(2768, 1111f<du>, 922f<du>, -438f<du>, 0f<du>, 555f<du>), 1357f<du>)
            |],
            [||])
    /// The n-ary intersection sign.
    let intersection =
        StretchyGlyph(
            Glyph(2765, 833f<du>, 782f<du>, -250f<du>, 0f<du>, 416f<du>),
            [|
                StretchSize(Glyph(2765, 833f<du>, 782f<du>, -250f<du>, 0f<du>, 416f<du>), 1023f<du>); StretchSize(Glyph(2766, 1111f<du>, 938f<du>, -422f<du>, 0f<du>, 555f<du>), 1357f<du>)
            |],
            [||])

/// Roots, whose surd grows to cover the radicand.
module Radicals =
    /// The tick and bar of a root, which grows to cover the radicand.
    let surd =
        StretchyGlyph(
            Glyph(3077, 833f<du>, 47f<du>, -969f<du>, 0f<du>, 416f<du>),
            [|
                StretchSize(Glyph(3077, 833f<du>, 47f<du>, -969f<du>, 0f<du>, 416f<du>), 1001f<du>); StretchSize(Glyph(3081, 1000f<du>, 860f<du>, -360f<du>, 0f<du>, 500f<du>), 1201f<du>)
                StretchSize(Glyph(3082, 1000f<du>, 1157f<du>, -657f<du>, 0f<du>, 500f<du>), 1801f<du>); StretchSize(Glyph(3083, 1000f<du>, 1454f<du>, -954f<du>, 0f<du>, 500f<du>), 2401f<du>)
                StretchSize(Glyph(3084, 1000f<du>, 1750f<du>, -1250f<du>, 0f<du>, 500f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(3078, 1056f<du>, 1829f<du>, 0f<du>, 0f<du>, 528f<du>), 0f<du>, 320f<du>, 1820f<du>, false)
                AssemblyPart(Glyph(3079, 1056f<du>, 641f<du>, 0f<du>, 0f<du>, 528f<du>), 640f<du>, 640f<du>, 640f<du>, true)
                AssemblyPart(Glyph(3080, 1056f<du>, 625f<du>, 0f<du>, 0f<du>, 528f<du>), 320f<du>, 0f<du>, 620f<du>, false)
            |])

/// Marks that grow along the line to span what they are set over or under.
module HorizontalMarks =
    /// The circumflex of \widehat, which grows to cover its base.
    let wideHat =
        StretchyGlyph(
            Glyph(2270, 0f<du>, 735f<du>, 578f<du>, 0f<du>, -264f<du>),
            [|
                StretchSize(Glyph(2270, 0f<du>, 735f<du>, 578f<du>, 0f<du>, -264f<du>), 365f<du>); StretchSize(Glyph(2280, 644f<du>, 750f<du>, 562f<du>, 0f<du>, 322f<du>), 645f<du>)
                StretchSize(Glyph(2290, 768f<du>, 750f<du>, 562f<du>, 0f<du>, 384f<du>), 769f<du>); StretchSize(Glyph(2300, 919f<du>, 750f<du>, 562f<du>, 0f<du>, 459f<du>), 920f<du>)
                StretchSize(Glyph(2310, 1100f<du>, 750f<du>, 562f<du>, 0f<du>, 550f<du>), 1101f<du>); StretchSize(Glyph(2320, 1320f<du>, 750f<du>, 562f<du>, 0f<du>, 660f<du>), 1321f<du>)
                StretchSize(Glyph(2330, 1581f<du>, 750f<du>, 562f<du>, 0f<du>, 790f<du>), 1582f<du>); StretchSize(Glyph(2340, 1896f<du>, 750f<du>, 562f<du>, 0f<du>, 948f<du>), 1897f<du>)
            |],
            [||])
    /// The tilde of \widetilde, which grows to cover its base.
    let wideTilde =
        StretchyGlyph(
            Glyph(2272, 0f<du>, 750f<du>, 546f<du>, 0f<du>, -264f<du>),
            [|
                StretchSize(Glyph(2272, 0f<du>, 750f<du>, 546f<du>, 0f<du>, -264f<du>), 371f<du>); StretchSize(Glyph(2282, 652f<du>, 750f<du>, 546f<du>, 0f<du>, 326f<du>), 653f<du>)
                StretchSize(Glyph(2292, 778f<du>, 766f<du>, 546f<du>, 0f<du>, 389f<du>), 779f<du>); StretchSize(Glyph(2302, 931f<du>, 766f<du>, 531f<du>, 0f<du>, 465f<du>), 932f<du>)
                StretchSize(Glyph(2312, 1115f<du>, 766f<du>, 531f<du>, 0f<du>, 557f<du>), 1116f<du>); StretchSize(Glyph(2322, 1335f<du>, 766f<du>, 531f<du>, 0f<du>, 667f<du>), 1336f<du>)
                StretchSize(Glyph(2332, 1599f<du>, 782f<du>, 531f<du>, 0f<du>, 799f<du>), 1600f<du>); StretchSize(Glyph(2342, 1915f<du>, 782f<du>, 515f<du>, 0f<du>, 957f<du>), 1916f<du>)
            |],
            [||])
    /// The brace of \overbrace.
    let overbrace =
        StretchyGlyph(
            Glyph(2359, 492f<du>, 782f<du>, 531f<du>, 28f<du>, 246f<du>),
            [|
                StretchSize(Glyph(2359, 492f<du>, 782f<du>, 531f<du>, 28f<du>, 246f<du>), 493f<du>); StretchSize(Glyph(2381, 993f<du>, 829f<du>, 500f<du>, 29f<du>, 496f<du>), 994f<du>)
                StretchSize(Glyph(2403, 1494f<du>, 829f<du>, 500f<du>, 28f<du>, 747f<du>), 1495f<du>); StretchSize(Glyph(2425, 1996f<du>, 829f<du>, 500f<du>, 28f<du>, 998f<du>), 1997f<du>)
                StretchSize(Glyph(2447, 2498f<du>, 844f<du>, 500f<du>, 28f<du>, 1249f<du>), 2499f<du>); StretchSize(Glyph(2469, 3000f<du>, 844f<du>, 500f<du>, 28f<du>, 1500f<du>), 3001f<du>)
                StretchSize(Glyph(2491, 3502f<du>, 844f<du>, 484f<du>, 28f<du>, 1751f<du>), 3503f<du>); StretchSize(Glyph(2545, 4006f<du>, 860f<du>, 484f<du>, 28f<du>, 2003f<du>), 4007f<du>)
            |],
            [|
                AssemblyPart(Glyph(2547, 1002f<du>, 735f<du>, 484f<du>, 0f<du>, 501f<du>), 0f<du>, 497f<du>, 1002f<du>, false)
                AssemblyPart(Glyph(2548, 994f<du>, 735f<du>, 609f<du>, 0f<du>, 497f<du>), 994f<du>, 994f<du>, 994f<du>, true)
                AssemblyPart(Glyph(2549, 2003f<du>, 860f<du>, 609f<du>, 0f<du>, 1001f<du>), 497f<du>, 497f<du>, 2003f<du>, false)
                AssemblyPart(Glyph(2548, 994f<du>, 735f<du>, 609f<du>, 0f<du>, 497f<du>), 994f<du>, 994f<du>, 994f<du>, true)
                AssemblyPart(Glyph(2550, 1001f<du>, 735f<du>, 484f<du>, 0f<du>, 500f<du>), 497f<du>, 0f<du>, 1001f<du>, false)
            |])
    /// The brace of \underbrace.
    let underbrace =
        StretchyGlyph(
            Glyph(2360, 492f<du>, -109f<du>, -360f<du>, 28f<du>, 246f<du>),
            [|
                StretchSize(Glyph(2360, 492f<du>, -109f<du>, -360f<du>, 28f<du>, 246f<du>), 493f<du>); StretchSize(Glyph(2382, 993f<du>, -78f<du>, -391f<du>, 28f<du>, 496f<du>), 994f<du>)
                StretchSize(Glyph(2404, 1494f<du>, -78f<du>, -391f<du>, 28f<du>, 747f<du>), 1495f<du>); StretchSize(Glyph(2426, 1996f<du>, -62f<du>, -407f<du>, 28f<du>, 998f<du>), 1997f<du>)
                StretchSize(Glyph(2448, 2498f<du>, -62f<du>, -407f<du>, 28f<du>, 1249f<du>), 2499f<du>); StretchSize(Glyph(2470, 3000f<du>, -62f<du>, -407f<du>, 28f<du>, 1500f<du>), 3001f<du>)
                StretchSize(Glyph(2492, 3502f<du>, -62f<du>, -422f<du>, 28f<du>, 1751f<du>), 3503f<du>); StretchSize(Glyph(2546, 4006f<du>, -62f<du>, -422f<du>, 28f<du>, 2003f<du>), 4007f<du>)
            |],
            [|
                AssemblyPart(Glyph(2551, 1002f<du>, -62f<du>, -297f<du>, 0f<du>, 501f<du>), 0f<du>, 497f<du>, 1002f<du>, false)
                AssemblyPart(Glyph(2552, 994f<du>, -187f<du>, -297f<du>, 0f<du>, 497f<du>), 994f<du>, 994f<du>, 994f<du>, true)
                AssemblyPart(Glyph(2553, 2003f<du>, -187f<du>, -422f<du>, 0f<du>, 1001f<du>), 497f<du>, 497f<du>, 2003f<du>, false)
                AssemblyPart(Glyph(2552, 994f<du>, -187f<du>, -297f<du>, 0f<du>, 497f<du>), 994f<du>, 994f<du>, 994f<du>, true)
                AssemblyPart(Glyph(2554, 1001f<du>, -62f<du>, -297f<du>, 0f<du>, 500f<du>), 497f<du>, 0f<du>, 1001f<du>, false)
            |])
    /// The arrow of \overrightarrow.
    let rightArrow =
        StretchyGlyph(
            Glyph(1817, 0f<du>, 719f<du>, 515f<du>, 0f<du>, -264f<du>),
            [|
                StretchSize(Glyph(1817, 0f<du>, 719f<du>, 515f<du>, 0f<du>, -264f<du>), 417f<du>); StretchSize(Glyph(1819, 659f<du>, 719f<du>, 515f<du>, 0f<du>, 329f<du>), 548f<du>)
            |],
            [|
                AssemblyPart(Glyph(1823, 205f<du>, 641f<du>, 593f<du>, 0f<du>, 102f<du>), 0f<du>, 69f<du>, 205f<du>, false)
                AssemblyPart(Glyph(1824, 137f<du>, 641f<du>, 593f<du>, 0f<du>, 68f<du>), 137f<du>, 137f<du>, 137f<du>, true)
                AssemblyPart(Glyph(1825, 205f<du>, 719f<du>, 515f<du>, 0f<du>, 102f<du>), 69f<du>, 0f<du>, 205f<du>, false)
            |])

module internal FontFile =
    /// The math face, which every glyph but a blackboard bold capital comes from.
    let byteLength = 733736
    let sha256 = "6075562b771f8b82f0c179e363389684f2dd09de30038269e2628e504bd7be0f"
    /// The blackboard face.
    let blackboardByteLength = 8716
    let blackboardSha256 = "9578b5b9c86e6ab03846080b9d6fa4f7bc6b3044ac15604b8e7bfd4330295dda"
