namespace ModeMath

// Generated by tools/MathTableGen from latinmodern-math.otf and AMS-Capital-Blackboard-Bold.otf,
// then cut down to modemath-math.otf by tools/trimfont.py. Do not edit.

/// Positioning values from the MATH table, in font design units.
module MathConstants =
    [<Literal>]
    let UnitsPerEm = 1000f<du>
    [<Literal>]
    let ScriptPercentScaleDown = 70f
    [<Literal>]
    let ScriptScriptPercentScaleDown = 50f
    [<Literal>]
    let DelimitedSubFormulaMinHeight = 1300f<du>
    [<Literal>]
    let DisplayOperatorMinHeight = 1300f<du>
    [<Literal>]
    let MathLeading = 154f<du>
    [<Literal>]
    let AxisHeight = 250f<du>
    [<Literal>]
    let AccentBaseHeight = 450f<du>
    [<Literal>]
    let FlattenedAccentBaseHeight = 664f<du>
    [<Literal>]
    let SubscriptShiftDown = 247f<du>
    [<Literal>]
    let SubscriptTopMax = 344f<du>
    [<Literal>]
    let SubscriptBaselineDropMin = 200f<du>
    [<Literal>]
    let SuperscriptShiftUp = 363f<du>
    [<Literal>]
    let SuperscriptShiftUpCramped = 289f<du>
    [<Literal>]
    let SuperscriptBottomMin = 108f<du>
    [<Literal>]
    let SuperscriptBaselineDropMax = 250f<du>
    [<Literal>]
    let SubSuperscriptGapMin = 160f<du>
    [<Literal>]
    let SuperscriptBottomMaxWithSubscript = 344f<du>
    [<Literal>]
    let SpaceAfterScript = 56f<du>
    [<Literal>]
    let UpperLimitGapMin = 200f<du>
    [<Literal>]
    let UpperLimitBaselineRiseMin = 111f<du>
    [<Literal>]
    let LowerLimitGapMin = 167f<du>
    [<Literal>]
    let LowerLimitBaselineDropMin = 600f<du>
    [<Literal>]
    let StackTopShiftUp = 444f<du>
    [<Literal>]
    let StackTopDisplayStyleShiftUp = 677f<du>
    [<Literal>]
    let StackBottomShiftDown = 345f<du>
    [<Literal>]
    let StackBottomDisplayStyleShiftDown = 686f<du>
    [<Literal>]
    let StackGapMin = 120f<du>
    [<Literal>]
    let StackDisplayStyleGapMin = 280f<du>
    [<Literal>]
    let StretchStackTopShiftUp = 111f<du>
    [<Literal>]
    let StretchStackBottomShiftDown = 600f<du>
    [<Literal>]
    let StretchStackGapAboveMin = 200f<du>
    [<Literal>]
    let StretchStackGapBelowMin = 167f<du>
    [<Literal>]
    let FractionNumeratorShiftUp = 394f<du>
    [<Literal>]
    let FractionNumeratorDisplayStyleShiftUp = 677f<du>
    [<Literal>]
    let FractionDenominatorShiftDown = 345f<du>
    [<Literal>]
    let FractionDenominatorDisplayStyleShiftDown = 686f<du>
    [<Literal>]
    let FractionNumeratorGapMin = 40f<du>
    [<Literal>]
    let FractionNumDisplayStyleGapMin = 120f<du>
    [<Literal>]
    let FractionRuleThickness = 40f<du>
    [<Literal>]
    let FractionDenominatorGapMin = 40f<du>
    [<Literal>]
    let FractionDenomDisplayStyleGapMin = 120f<du>
    [<Literal>]
    let SkewedFractionHorizontalGap = 350f<du>
    [<Literal>]
    let SkewedFractionVerticalGap = 96f<du>
    [<Literal>]
    let OverbarVerticalGap = 120f<du>
    [<Literal>]
    let OverbarRuleThickness = 40f<du>
    [<Literal>]
    let OverbarExtraAscender = 40f<du>
    [<Literal>]
    let UnderbarVerticalGap = 120f<du>
    [<Literal>]
    let UnderbarRuleThickness = 40f<du>
    [<Literal>]
    let UnderbarExtraDescender = 40f<du>
    [<Literal>]
    let RadicalVerticalGap = 50f<du>
    [<Literal>]
    let RadicalDisplayStyleVerticalGap = 148f<du>
    [<Literal>]
    let RadicalRuleThickness = 40f<du>
    [<Literal>]
    let RadicalExtraAscender = 40f<du>
    [<Literal>]
    let RadicalKernBeforeDegree = 278f<du>
    [<Literal>]
    let RadicalKernAfterDegree = -556f<du>
    [<Literal>]
    let RadicalDegreeBottomRaisePercent = 60f
    [<Literal>]
    let MinConnectorOverlap = 20f<du>

/// The alphabets a variable is set in, indexed from the first letter of each.
module internal Alphabets =
    /// Math italic, a to z, in which variables are set.
    let italicSmall: Glyph array =
        [|
            Glyph(134, 529f<du>, 454f<du>, -16f<du>, 0f<du>, 287f<du>); Glyph(135, 429f<du>, 704f<du>, -16f<du>, 14f<du>, 165f<du>)
            Glyph(136, 433f<du>, 454f<du>, -16f<du>, 25f<du>, 317f<du>); Glyph(137, 520f<du>, 704f<du>, -16f<du>, 24f<du>, 442f<du>)
            Glyph(138, 466f<du>, 454f<du>, -16f<du>, 0f<du>, 300f<du>); Glyph(139, 490f<du>, 704f<du>, -204f<du>, 90f<du>, 464f<du>)
            Glyph(140, 477f<du>, 454f<du>, -204f<du>, 25f<du>, 316f<du>); Glyph(141, 576f<du>, 704f<du>, -16f<du>, 0f<du>, 213f<du>)
            Glyph(142, 345f<du>, 672f<du>, -16f<du>, 0f<du>, 247f<du>); Glyph(143, 412f<du>, 672f<du>, -204f<du>, 13f<du>, 359f<du>)
            Glyph(144, 521f<du>, 704f<du>, -16f<du>, 15f<du>, 213f<du>); Glyph(145, 298f<du>, 704f<du>, -16f<du>, 0f<du>, 184f<du>)
            Glyph(146, 878f<du>, 454f<du>, -16f<du>, 0f<du>, 404f<du>); Glyph(147, 600f<du>, 454f<du>, -16f<du>, 0f<du>, 265f<du>)
            Glyph(148, 485f<du>, 454f<du>, -16f<du>, 12f<du>, 315f<du>); Glyph(149, 503f<du>, 454f<du>, -204f<du>, 15f<du>, 246f<du>)
            Glyph(150, 446f<du>, 454f<du>, -204f<du>, 34f<du>, 349f<du>); Glyph(151, 451f<du>, 454f<du>, -16f<du>, 13f<du>, 247f<du>)
            Glyph(152, 469f<du>, 454f<du>, -16f<du>, 0f<du>, 296f<du>); Glyph(153, 361f<du>, 625f<du>, -16f<du>, 0f<du>, 225f<du>)
            Glyph(154, 572f<du>, 454f<du>, -16f<du>, 0f<du>, 305f<du>); Glyph(155, 485f<du>, 454f<du>, -16f<du>, 11f<du>, 294f<du>)
            Glyph(156, 716f<du>, 454f<du>, -16f<du>, 3f<du>, 405f<du>); Glyph(157, 572f<du>, 454f<du>, -16f<du>, 0f<du>, 329f<du>)
            Glyph(158, 490f<du>, 454f<du>, -204f<du>, 28f<du>, 304f<du>); Glyph(159, 465f<du>, 454f<du>, -16f<du>, 30f<du>, 336f<du>)
        |]
    /// Math italic, A to Z.
    let italicCapital: Glyph array =
        [|
            Glyph(108, 750f<du>, 719f<du>, 0f<du>, 0f<du>, 550f<du>); Glyph(109, 759f<du>, 688f<du>, 0f<du>, 25f<du>, 420f<du>)
            Glyph(110, 715f<du>, 704f<du>, -32f<du>, 73f<du>, 596f<du>); Glyph(111, 828f<du>, 688f<du>, 0f<du>, 4f<du>, 427f<du>)
            Glyph(112, 738f<du>, 688f<du>, 0f<du>, 54f<du>, 483f<du>); Glyph(113, 643f<du>, 688f<du>, 0f<du>, 134f<du>, 475f<du>)
            Glyph(114, 786f<du>, 704f<du>, -32f<du>, 0f<du>, 596f<du>); Glyph(115, 831f<du>, 688f<du>, 0f<du>, 78f<du>, 542f<du>)
            Glyph(116, 440f<du>, 688f<du>, 0f<du>, 85f<du>, 347f<du>); Glyph(117, 555f<du>, 688f<du>, -32f<du>, 106f<du>, 487f<du>)
            Glyph(118, 849f<du>, 688f<du>, 0f<du>, 68f<du>, 545f<du>); Glyph(119, 681f<du>, 688f<du>, 0f<du>, 0f<du>, 360f<du>)
            Glyph(120, 970f<du>, 688f<du>, 0f<du>, 102f<du>, 625f<du>); Glyph(121, 803f<du>, 688f<du>, 0f<du>, 106f<du>, 542f<du>)
            Glyph(122, 763f<du>, 704f<du>, -32f<du>, 5f<du>, 495f<du>); Glyph(123, 642f<du>, 688f<du>, 0f<du>, 140f<du>, 416f<du>)
            Glyph(124, 791f<du>, 704f<du>, -204f<du>, 0f<du>, 495f<du>); Glyph(125, 759f<du>, 688f<du>, -32f<du>, 24f<du>, 398f<du>)
            Glyph(126, 613f<du>, 704f<du>, -32f<du>, 60f<du>, 498f<du>); Glyph(127, 584f<du>, 688f<du>, 0f<du>, 148f<du>, 398f<du>)
            Glyph(128, 683f<du>, 688f<du>, -32f<du>, 105f<du>, 421f<du>); Glyph(129, 583f<du>, 688f<du>, -32f<du>, 214f<du>, 413f<du>)
            Glyph(130, 944f<du>, 688f<du>, -32f<du>, 132f<du>, 552f<du>); Glyph(131, 828f<du>, 688f<du>, 0f<du>, 51f<du>, 528f<du>)
            Glyph(132, 581f<du>, 688f<du>, 0f<du>, 209f<du>, 399f<du>); Glyph(133, 683f<du>, 688f<du>, 0f<du>, 68f<du>, 485f<du>)
        |]
    /// Math italic, alpha to omega.
    let italicGreek: Glyph array =
        [|
            Glyph(536, 640f<du>, 454f<du>, -16f<du>, 0f<du>, 392f<du>); Glyph(537, 566f<du>, 719f<du>, -204f<du>, 36f<du>, 437f<du>)
            Glyph(538, 518f<du>, 454f<du>, -219f<du>, 53f<du>, 259f<du>); Glyph(539, 444f<du>, 719f<du>, -16f<du>, 36f<du>, 335f<du>)
            Glyph(560, 466f<du>, 454f<du>, -32f<du>, 0f<du>, 284f<du>); Glyph(541, 438f<du>, 704f<du>, -204f<du>, 64f<du>, 313f<du>)
            Glyph(542, 497f<du>, 454f<du>, -219f<du>, 27f<du>, 272f<du>); Glyph(543, 469f<du>, 704f<du>, -16f<du>, 14f<du>, 310f<du>)
            Glyph(544, 354f<du>, 454f<du>, -16f<du>, 0f<du>, 184f<du>); Glyph(545, 576f<du>, 454f<du>, -16f<du>, 0f<du>, 331f<du>)
            Glyph(547, 583f<du>, 704f<du>, -16f<du>, 0f<du>, 238f<du>); Glyph(548, 603f<du>, 454f<du>, -219f<du>, 0f<du>, 349f<du>)
            Glyph(549, 494f<du>, 454f<du>, 0f<du>, 58f<du>, 297f<du>); Glyph(550, 438f<du>, 704f<du>, -204f<du>, 36f<du>, 285f<du>)
            Glyph(567, 485f<du>, 454f<du>, -16f<du>, 12f<du>, 243f<du>); Glyph(551, 570f<du>, 438f<du>, -16f<du>, 25f<du>, 328f<du>)
            Glyph(552, 517f<du>, 454f<du>, -219f<du>, 13f<du>, 354f<du>); Glyph(564, 363f<du>, 454f<du>, -110f<du>, 74f<du>, 182f<du>)
            Glyph(553, 571f<du>, 438f<du>, -16f<du>, 24f<du>, 286f<du>); Glyph(554, 437f<du>, 438f<du>, -16f<du>, 102f<du>, 269f<du>)
            Glyph(555, 540f<du>, 454f<du>, -16f<du>, 12f<du>, 306f<du>); Glyph(565, 654f<du>, 454f<du>, -219f<du>, 0f<du>, 355f<du>)
            Glyph(557, 626f<du>, 454f<du>, -204f<du>, 0f<du>, 331f<du>); Glyph(558, 651f<du>, 704f<du>, -204f<du>, 12f<du>, 469f<du>)
            Glyph(559, 622f<du>, 454f<du>, -16f<du>, 10f<du>, 345f<du>)
        |]
    /// Math bold italic, a to z.
    let boldSmall: Glyph array =
        [|
            Glyph(186, 633f<du>, 454f<du>, -16f<du>, 0f<du>, 336f<du>); Glyph(187, 521f<du>, 704f<du>, -16f<du>, 13f<du>, 225f<du>)
            Glyph(188, 513f<du>, 454f<du>, -16f<du>, 26f<du>, 365f<du>); Glyph(189, 610f<du>, 704f<du>, -16f<du>, 22f<du>, 512f<du>)
            Glyph(190, 554f<du>, 454f<du>, -16f<du>, 0f<du>, 340f<du>); Glyph(191, 568f<du>, 704f<du>, -204f<du>, 86f<du>, 516f<du>)
            Glyph(192, 545f<du>, 454f<du>, -204f<du>, 17f<du>, 339f<du>); Glyph(193, 668f<du>, 704f<du>, -16f<du>, 0f<du>, 228f<du>)
            Glyph(194, 405f<du>, 704f<du>, -16f<du>, 0f<du>, 282f<du>); Glyph(195, 471f<du>, 704f<du>, -204f<du>, 7f<du>, 398f<du>)
            Glyph(196, 604f<du>, 704f<du>, -16f<du>, 0f<du>, 228f<du>); Glyph(197, 348f<du>, 704f<du>, -16f<du>, 0f<du>, 196f<du>)
            Glyph(198, 1032f<du>, 454f<du>, -16f<du>, 0f<du>, 478f<du>); Glyph(199, 713f<du>, 454f<du>, -16f<du>, 0f<du>, 318f<du>)
            Glyph(200, 585f<du>, 454f<du>, -16f<du>, 12f<du>, 367f<du>); Glyph(201, 601f<du>, 454f<du>, -204f<du>, 13f<du>, 296f<du>)
            Glyph(202, 542f<du>, 454f<du>, -204f<du>, 29f<du>, 410f<du>); Glyph(203, 529f<du>, 454f<du>, -16f<du>, 4f<du>, 282f<du>)
            Glyph(204, 531f<du>, 454f<du>, -16f<du>, 0f<du>, 324f<du>); Glyph(205, 415f<du>, 657f<du>, -16f<du>, 0f<du>, 254f<du>)
            Glyph(206, 681f<du>, 454f<du>, -16f<du>, 0f<du>, 345f<du>); Glyph(207, 567f<du>, 454f<du>, -16f<du>, 0f<du>, 332f<du>)
            Glyph(208, 831f<du>, 454f<du>, -16f<du>, 0f<du>, 460f<du>); Glyph(209, 659f<du>, 454f<du>, -16f<du>, 0f<du>, 359f<du>)
            Glyph(210, 590f<du>, 454f<du>, -204f<du>, 20f<du>, 345f<du>); Glyph(211, 555f<du>, 454f<du>, -16f<du>, 11f<du>, 379f<du>)
        |]
    /// Math bold italic, A to Z.
    let boldCapital: Glyph array =
        [|
            Glyph(160, 869f<du>, 719f<du>, 0f<du>, 0f<du>, 608f<du>); Glyph(161, 866f<du>, 688f<du>, 0f<du>, 16f<du>, 477f<du>)
            Glyph(162, 817f<du>, 704f<du>, -16f<du>, 66f<du>, 658f<du>); Glyph(163, 938f<du>, 688f<du>, 0f<du>, 5f<du>, 465f<du>)
            Glyph(164, 810f<du>, 688f<du>, 0f<du>, 43f<du>, 515f<du>); Glyph(165, 689f<du>, 688f<du>, 0f<du>, 148f<du>, 507f<du>)
            Glyph(166, 887f<du>, 704f<du>, -16f<du>, 0f<du>, 658f<du>); Glyph(167, 982f<du>, 688f<du>, 0f<du>, 73f<du>, 616f<du>)
            Glyph(168, 511f<du>, 688f<du>, 0f<du>, 83f<du>, 383f<du>); Glyph(169, 631f<du>, 688f<du>, -16f<du>, 91f<du>, 516f<du>)
            Glyph(170, 971f<du>, 688f<du>, 0f<du>, 60f<du>, 604f<du>); Glyph(171, 756f<du>, 688f<du>, 0f<du>, 0f<du>, 396f<du>)
            Glyph(172, 1142f<du>, 688f<du>, 0f<du>, 102f<du>, 712f<du>); Glyph(173, 950f<du>, 688f<du>, 0f<du>, 105f<du>, 616f<du>)
            Glyph(174, 837f<du>, 704f<du>, -16f<du>, 6f<du>, 528f<du>); Glyph(175, 723f<du>, 688f<du>, 0f<du>, 154f<du>, 468f<du>)
            Glyph(176, 869f<du>, 704f<du>, -204f<du>, 0f<du>, 528f<du>); Glyph(177, 872f<du>, 688f<du>, -16f<du>, 37f<du>, 457f<du>)
            Glyph(178, 693f<du>, 704f<du>, -16f<du>, 49f<du>, 561f<du>); Glyph(179, 637f<du>, 688f<du>, 0f<du>, 163f<du>, 434f<du>)
            Glyph(180, 800f<du>, 688f<du>, -16f<du>, 105f<du>, 473f<du>); Glyph(181, 678f<du>, 688f<du>, -16f<du>, 235f<du>, 476f<du>)
            Glyph(182, 1093f<du>, 688f<du>, -16f<du>, 142f<du>, 637f<du>); Glyph(183, 947f<du>, 688f<du>, 0f<du>, 34f<du>, 584f<du>)
            Glyph(184, 675f<du>, 688f<du>, 0f<du>, 228f<du>, 460f<du>); Glyph(185, 773f<du>, 688f<du>, 0f<du>, 60f<du>, 533f<du>)
        |]
    /// Upright a to z, in which function names are set.
    let uprightSmall: Glyph array =
        [|
            Glyph(64, 500f<du>, 454f<du>, -16f<du>, 11f<du>, 214f<du>); Glyph(65, 556f<du>, 704f<du>, -16f<du>, 0f<du>, 100f<du>)
            Glyph(66, 444f<du>, 454f<du>, -16f<du>, 0f<du>, 249f<du>); Glyph(67, 556f<du>, 704f<du>, -16f<du>, 0f<du>, 377f<du>)
            Glyph(68, 444f<du>, 454f<du>, -16f<du>, 0f<du>, 236f<du>); Glyph(69, 306f<du>, 704f<du>, 0f<du>, 79f<du>, 262f<du>)
            Glyph(70, 500f<du>, 454f<du>, -219f<du>, 13f<du>, 332f<du>); Glyph(71, 556f<du>, 704f<du>, 0f<du>, 7f<du>, 104f<du>)
            Glyph(72, 278f<du>, 657f<du>, 0f<du>, 0f<du>, 138f<du>); Glyph(73, 306f<du>, 657f<du>, -204f<du>, 0f<du>, 156f<du>)
            Glyph(74, 528f<du>, 704f<du>, 0f<du>, 11f<du>, 100f<du>); Glyph(75, 278f<du>, 704f<du>, 0f<du>, 5f<du>, 105f<du>)
            Glyph(76, 833f<du>, 454f<du>, 0f<du>, 8f<du>, 350f<du>); Glyph(77, 556f<du>, 454f<du>, 0f<du>, 7f<du>, 211f<du>)
            Glyph(78, 500f<du>, 454f<du>, -16f<du>, 0f<du>, 249f<du>); Glyph(79, 556f<du>, 454f<du>, -204f<du>, 0f<du>, 202f<du>)
            Glyph(80, 528f<du>, 454f<du>, -204f<du>, 27f<du>, 318f<du>); Glyph(81, 392f<du>, 454f<du>, 0f<du>, 0f<du>, 181f<du>)
            Glyph(82, 394f<du>, 454f<du>, -16f<du>, 0f<du>, 232f<du>); Glyph(83, 389f<du>, 625f<du>, -16f<du>, 0f<du>, 161f<du>)
            Glyph(84, 556f<du>, 454f<du>, -16f<du>, 7f<du>, 245f<du>); Glyph(85, 528f<du>, 438f<du>, -16f<du>, 8f<du>, 264f<du>)
            Glyph(86, 722f<du>, 438f<du>, -16f<du>, 9f<du>, 361f<du>); Glyph(87, 528f<du>, 438f<du>, 0f<du>, 16f<du>, 258f<du>)
            Glyph(88, 528f<du>, 438f<du>, -204f<du>, 8f<du>, 264f<du>); Glyph(89, 444f<du>, 438f<du>, 0f<du>, 0f<du>, 226f<du>)
        |]
    /// Upright A to Z.
    let uprightCapital: Glyph array =
        [|
            Glyph(33, 750f<du>, 719f<du>, 0f<du>, 0f<du>, 375f<du>); Glyph(34, 708f<du>, 688f<du>, 0f<du>, 0f<du>, 256f<du>)
            Glyph(35, 722f<du>, 704f<du>, -32f<du>, 0f<du>, 507f<du>); Glyph(36, 764f<du>, 688f<du>, 0f<du>, 0f<du>, 243f<du>)
            Glyph(37, 681f<du>, 688f<du>, 0f<du>, 0f<du>, 315f<du>); Glyph(38, 653f<du>, 688f<du>, 0f<du>, 0f<du>, 308f<du>)
            Glyph(39, 785f<du>, 704f<du>, -32f<du>, 0f<du>, 507f<du>); Glyph(40, 750f<du>, 688f<du>, 0f<du>, 0f<du>, 375f<du>)
            Glyph(41, 361f<du>, 688f<du>, 0f<du>, 0f<du>, 181f<du>); Glyph(42, 514f<du>, 688f<du>, -32f<du>, 0f<du>, 317f<du>)
            Glyph(43, 778f<du>, 688f<du>, 0f<du>, 0f<du>, 378f<du>); Glyph(44, 625f<du>, 688f<du>, 0f<du>, 0f<du>, 193f<du>)
            Glyph(45, 917f<du>, 688f<du>, 0f<du>, 0f<du>, 458f<du>); Glyph(46, 750f<du>, 688f<du>, 0f<du>, 0f<du>, 375f<du>)
            Glyph(47, 778f<du>, 704f<du>, -32f<du>, 0f<du>, 388f<du>); Glyph(48, 681f<du>, 688f<du>, 0f<du>, 0f<du>, 250f<du>)
            Glyph(49, 778f<du>, 704f<du>, -204f<du>, 0f<du>, 388f<du>); Glyph(50, 736f<du>, 688f<du>, -32f<du>, 24f<du>, 234f<du>)
            Glyph(51, 556f<du>, 704f<du>, -32f<du>, 0f<du>, 330f<du>); Glyph(52, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>)
            Glyph(53, 750f<du>, 688f<du>, -32f<du>, 0f<du>, 375f<du>); Glyph(54, 750f<du>, 688f<du>, -32f<du>, 8f<du>, 375f<du>)
            Glyph(55, 1028f<du>, 688f<du>, -32f<du>, 9f<du>, 514f<du>); Glyph(56, 750f<du>, 688f<du>, 0f<du>, 4f<du>, 361f<du>)
            Glyph(57, 750f<du>, 688f<du>, 0f<du>, 16f<du>, 375f<du>); Glyph(58, 611f<du>, 688f<du>, 0f<du>, 0f<du>, 317f<du>)
        |]
    /// Upright Alpha to Omega, as capital Greek is set.
    let uprightGreekCapital: Glyph array =
        [|
            Glyph(496, 750f<du>, 719f<du>, 0f<du>, 0f<du>, 374f<du>); Glyph(497, 708f<du>, 688f<du>, 0f<du>, 0f<du>, 286f<du>)
            Glyph(486, 625f<du>, 688f<du>, 0f<du>, 0f<du>, 297f<du>); Glyph(485, 833f<du>, 719f<du>, 0f<du>, 0f<du>, 416f<du>)
            Glyph(498, 681f<du>, 688f<du>, 0f<du>, 0f<du>, 318f<du>); Glyph(499, 611f<du>, 688f<du>, 0f<du>, 0f<du>, 316f<du>)
            Glyph(500, 750f<du>, 688f<du>, 0f<du>, 0f<du>, 375f<du>); Glyph(493, 778f<du>, 704f<du>, -32f<du>, 0f<du>, 389f<du>)
            Glyph(501, 361f<du>, 688f<du>, 0f<du>, 0f<du>, 181f<du>); Glyph(502, 778f<du>, 688f<du>, 0f<du>, 0f<du>, 378f<du>)
            Glyph(487, 694f<du>, 719f<du>, 0f<du>, 0f<du>, 347f<du>); Glyph(503, 917f<du>, 688f<du>, 0f<du>, 0f<du>, 458f<du>)
            Glyph(504, 750f<du>, 688f<du>, 0f<du>, 0f<du>, 375f<du>); Glyph(495, 667f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)
            Glyph(505, 778f<du>, 704f<du>, -32f<du>, 0f<du>, 389f<du>); Glyph(490, 750f<du>, 688f<du>, 0f<du>, 0f<du>, 375f<du>)
            Glyph(506, 681f<du>, 688f<du>, 0f<du>, 0f<du>, 283f<du>); Glyph(0, 0f<du>, 0f<du>, 0f<du>, 0f<du>, 0f<du>)
            Glyph(492, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 350f<du>); Glyph(507, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>)
            Glyph(494, 778f<du>, 704f<du>, 0f<du>, 0f<du>, 389f<du>); Glyph(489, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 358f<du>)
            Glyph(508, 750f<du>, 688f<du>, 0f<du>, 4f<du>, 361f<du>); Glyph(491, 778f<du>, 688f<du>, 0f<du>, 0f<du>, 386f<du>)
            Glyph(488, 722f<du>, 704f<du>, 0f<du>, 0f<du>, 360f<du>)
        |]
    /// Upright alpha to omega, as \mathrm sets small Greek.
    let uprightGreekSmall: Glyph array =
        [|
            Glyph(509, 641f<du>, 454f<du>, -16f<du>, 24f<du>, 356f<du>); Glyph(510, 558f<du>, 719f<du>, -204f<du>, 0f<du>, 280f<du>)
            Glyph(511, 586f<du>, 454f<du>, -219f<du>, 0f<du>, 293f<du>); Glyph(512, 474f<du>, 719f<du>, -16f<du>, 0f<du>, 232f<du>)
            Glyph(530, 535f<du>, 454f<du>, -32f<du>, 0f<du>, 244f<du>); Glyph(513, 530f<du>, 704f<du>, -204f<du>, 0f<du>, 224f<du>)
            Glyph(514, 530f<du>, 454f<du>, -219f<du>, 0f<du>, 218f<du>); Glyph(515, 488f<du>, 704f<du>, -16f<du>, 0f<du>, 247f<du>)
            Glyph(516, 308f<du>, 454f<du>, -16f<du>, 24f<du>, 98f<du>); Glyph(517, 530f<du>, 454f<du>, -16f<du>, 23f<du>, 247f<du>)
            Glyph(518, 537f<du>, 704f<du>, -16f<du>, 54f<du>, 86f<du>); Glyph(519, 530f<du>, 454f<du>, -219f<du>, 23f<du>, 237f<du>)
            Glyph(520, 502f<du>, 454f<du>, 0f<du>, 0f<du>, 209f<du>); Glyph(521, 530f<du>, 704f<du>, -204f<du>, 0f<du>, 196f<du>)
            Glyph(534, 500f<du>, 454f<du>, -16f<du>, 0f<du>, 250f<du>); Glyph(522, 586f<du>, 438f<du>, -16f<du>, 0f<du>, 279f<du>)
            Glyph(523, 488f<du>, 454f<du>, -219f<du>, 0f<du>, 243f<du>); Glyph(531, 474f<du>, 454f<du>, -110f<du>, 0f<du>, 237f<du>)
            Glyph(524, 599f<du>, 438f<du>, -16f<du>, 0f<du>, 300f<du>); Glyph(525, 530f<du>, 438f<du>, -16f<du>, 0f<du>, 232f<du>)
            Glyph(526, 530f<du>, 454f<du>, -16f<du>, 0f<du>, 251f<du>); Glyph(532, 641f<du>, 454f<du>, -219f<du>, 0f<du>, 302f<du>)
            Glyph(527, 641f<du>, 454f<du>, -204f<du>, 24f<du>, 267f<du>); Glyph(528, 641f<du>, 704f<du>, -204f<du>, 0f<du>, 348f<du>)
            Glyph(529, 641f<du>, 454f<du>, -16f<du>, 0f<du>, 322f<du>)
        |]
    /// Upright 0 to 9.
    let digits: Glyph array =
        [|
            Glyph(16, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 254f<du>); Glyph(17, 500f<du>, 672f<du>, 0f<du>, 0f<du>, 257f<du>)
            Glyph(18, 500f<du>, 672f<du>, 0f<du>, 0f<du>, 240f<du>); Glyph(19, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 258f<du>)
            Glyph(20, 500f<du>, 688f<du>, 0f<du>, 0f<du>, 353f<du>); Glyph(21, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 256f<du>)
            Glyph(22, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 318f<du>); Glyph(23, 500f<du>, 688f<du>, -32f<du>, 13f<du>, 103f<du>)
            Glyph(24, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 261f<du>); Glyph(25, 500f<du>, 672f<du>, -32f<du>, 0f<du>, 242f<du>)
        |]
    /// The italic shapes Unicode keeps outside the alphabets.
    let italicShapes: CG array =
        [|
            CG(8706, Glyph(566, 531f<du>, 719f<du>, -32f<du>, 63f<du>, 361f<du>)); CG(1013, Glyph(540, 406f<du>, 438f<du>, -16f<du>, 0f<du>, 269f<du>))
            CG(977, Glyph(561, 591f<du>, 704f<du>, -16f<du>, 0f<du>, 411f<du>)); CG(1008, Glyph(546, 624f<du>, 454f<du>, -16f<du>, 0f<du>, 365f<du>))
            CG(981, Glyph(556, 596f<du>, 704f<du>, -204f<du>, 5f<du>, 423f<du>)); CG(1009, Glyph(563, 517f<du>, 454f<du>, -204f<du>, 13f<du>, 361f<du>))
            CG(982, Glyph(562, 828f<du>, 438f<du>, -16f<du>, 17f<du>, 453f<du>))
        |]
    /// Blackboard bold A to Z, which the second face is carried for.
    let blackboardCapital: Glyph array =
        [|
            Glyph(Face.Blackboard, 1, 722f<du>, 704f<du>, 0f<du>, 0f<du>, 361f<du>); Glyph(Face.Blackboard, 2, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)
            Glyph(Face.Blackboard, 3, 722f<du>, 704f<du>, -32f<du>, 0f<du>, 361f<du>); Glyph(Face.Blackboard, 4, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>)
            Glyph(Face.Blackboard, 5, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>); Glyph(Face.Blackboard, 6, 611f<du>, 688f<du>, 0f<du>, 0f<du>, 305f<du>)
            Glyph(Face.Blackboard, 7, 777f<du>, 704f<du>, -32f<du>, 0f<du>, 388f<du>); Glyph(Face.Blackboard, 8, 777f<du>, 688f<du>, 0f<du>, 0f<du>, 388f<du>)
            Glyph(Face.Blackboard, 9, 388f<du>, 688f<du>, 0f<du>, 0f<du>, 194f<du>); Glyph(Face.Blackboard, 10, 500f<du>, 688f<du>, -79f<du>, 0f<du>, 250f<du>)
            Glyph(Face.Blackboard, 11, 777f<du>, 688f<du>, 0f<du>, 0f<du>, 388f<du>); Glyph(Face.Blackboard, 12, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)
            Glyph(Face.Blackboard, 13, 944f<du>, 688f<du>, 0f<du>, 0f<du>, 472f<du>); Glyph(Face.Blackboard, 14, 722f<du>, 688f<du>, -32f<du>, 0f<du>, 361f<du>)
            Glyph(Face.Blackboard, 15, 777f<du>, 704f<du>, -32f<du>, 0f<du>, 388f<du>); Glyph(Face.Blackboard, 16, 611f<du>, 688f<du>, 0f<du>, 0f<du>, 305f<du>)
            Glyph(Face.Blackboard, 17, 777f<du>, 704f<du>, -188f<du>, 0f<du>, 388f<du>); Glyph(Face.Blackboard, 18, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>)
            Glyph(Face.Blackboard, 19, 555f<du>, 704f<du>, -16f<du>, 0f<du>, 277f<du>); Glyph(Face.Blackboard, 20, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)
            Glyph(Face.Blackboard, 21, 722f<du>, 688f<du>, -32f<du>, 0f<du>, 361f<du>); Glyph(Face.Blackboard, 22, 722f<du>, 688f<du>, -32f<du>, 0f<du>, 361f<du>)
            Glyph(Face.Blackboard, 23, 1000f<du>, 688f<du>, -32f<du>, 0f<du>, 500f<du>); Glyph(Face.Blackboard, 24, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>)
            Glyph(Face.Blackboard, 25, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>); Glyph(Face.Blackboard, 26, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)
        |]

/// Every character a formula may hold that no alphabet covers, ascending by codepoint.
module internal Repertoire =
    let all: CG array =
        [|
            CG(32, Glyph(1, 332f<du>, 0f<du>, 0f<du>, 0f<du>, 166f<du>)); CG(33, Glyph(2, 278f<du>, 719f<du>, 0f<du>, 0f<du>, 139f<du>))
            CG(34, Glyph(3, 374f<du>, 704f<du>, 421f<du>, 0f<du>, 187f<du>)); CG(35, Glyph(4, 833f<du>, 704f<du>, -204f<du>, 0f<du>, 416f<du>))
            CG(36, Glyph(5, 500f<du>, 750f<du>, -63f<du>, 0f<du>, 250f<du>)); CG(37, Glyph(6, 833f<du>, 750f<du>, -63f<du>, 0f<du>, 416f<du>))
            CG(38, Glyph(7, 778f<du>, 719f<du>, -32f<du>, 0f<du>, 389f<du>)); CG(39, Glyph(95, 278f<du>, 704f<du>, 421f<du>, 0f<du>, 139f<du>))
            CG(40, Glyph(8, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>)); CG(41, Glyph(9, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>))
            CG(42, Glyph(10, 500f<du>, 750f<du>, 312f<du>, 0f<du>, 398f<du>)); CG(43, Glyph(11, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>))
            CG(44, Glyph(12, 278f<du>, 110f<du>, -204f<du>, 0f<du>, 139f<du>)); CG(45, Glyph(13, 333f<du>, 250f<du>, 187f<du>, 0f<du>, 166f<du>))
            CG(46, Glyph(14, 278f<du>, 110f<du>, 0f<du>, 0f<du>, 139f<du>)); CG(47, Glyph(15, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>))
            CG(58, Glyph(26, 278f<du>, 438f<du>, 0f<du>, 0f<du>, 139f<du>)); CG(59, Glyph(27, 278f<du>, 438f<du>, -204f<du>, 0f<du>, 139f<du>))
            CG(60, Glyph(28, 778f<du>, 547f<du>, -47f<du>, 0f<du>, 389f<du>)); CG(61, Glyph(29, 778f<du>, 375f<du>, 125f<du>, 0f<du>, 389f<du>))
            CG(62, Glyph(30, 778f<du>, 547f<du>, -47f<du>, 0f<du>, 389f<du>)); CG(63, Glyph(31, 472f<du>, 704f<du>, 0f<du>, 0f<du>, 236f<du>))
            CG(64, Glyph(32, 778f<du>, 704f<du>, -16f<du>, 0f<du>, 389f<du>)); CG(91, Glyph(59, 278f<du>, 750f<du>, -250f<du>, 6f<du>, 139f<du>))
            CG(92, Glyph(60, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>)); CG(93, Glyph(61, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>))
            CG(94, Glyph(62, 556f<du>, 750f<du>, 562f<du>, 33f<du>, 278f<du>)); CG(95, Glyph(63, 333f<du>, -93f<du>, -141f<du>, 28f<du>, 166f<du>))
            CG(96, Glyph(102, 500f<du>, 704f<du>, 500f<du>, 0f<du>, 219f<du>)); CG(123, Glyph(90, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>))
            CG(124, Glyph(91, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>)); CG(125, Glyph(92, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>))
            CG(126, Glyph(93, 556f<du>, 313f<du>, 187f<du>, 27f<du>, 278f<du>)); CG(163, Glyph(94, 750f<du>, 688f<du>, -47f<du>, 0f<du>, 375f<du>))
            CG(172, Glyph(423, 667f<du>, 375f<du>, 125f<du>, 0f<du>, 333f<du>)); CG(176, Glyph(104, 375f<du>, 688f<du>, 406f<du>, 0f<du>, 187f<du>))
            CG(177, Glyph(390, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>)); CG(181, Glyph(105, 556f<du>, 454f<du>, -204f<du>, 6f<du>, 278f<du>))
            CG(215, Glyph(400, 778f<du>, 500f<du>, 0f<du>, 0f<du>, 389f<du>)); CG(247, Glyph(392, 778f<du>, 516f<du>, -16f<du>, 0f<du>, 389f<du>))
            CG(8211, Glyph(96, 500f<du>, 282f<du>, 250f<du>, 27f<du>, 250f<du>)); CG(8224, Glyph(97, 444f<du>, 704f<du>, -219f<du>, 0f<du>, 222f<du>))
            CG(8225, Glyph(98, 444f<du>, 704f<du>, -204f<du>, 0f<du>, 222f<du>)); CG(8226, Glyph(99, 500f<du>, 454f<du>, 46f<du>, 0f<du>, 250f<du>))
            CG(8230, Glyph(100, 837f<du>, 110f<du>, 0f<du>, 0f<du>, 418f<du>)); CG(8240, Glyph(101, 1140f<du>, 750f<du>, -63f<du>, 0f<du>, 570f<du>))
            CG(8242, Glyph(455, 311f<du>, 750f<du>, 421f<du>, 0f<du>, 155f<du>)); CG(8243, Glyph(456, 511f<du>, 750f<du>, 421f<du>, 0f<du>, 255f<du>))
            CG(8450, Glyph(477, 667f<du>, 704f<du>, -32f<du>, 0f<du>, 335f<du>)); CG(8461, Glyph(478, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>))
            CG(8467, Glyph(107, 417f<du>, 704f<du>, -16f<du>, 9f<du>, 208f<du>)); CG(8469, Glyph(479, 722f<du>, 688f<du>, 0f<du>, 0f<du>, 361f<du>))
            CG(8473, Glyph(480, 639f<du>, 688f<du>, 0f<du>, 0f<du>, 247f<du>)); CG(8474, Glyph(481, 667f<du>, 704f<du>, -204f<du>, 0f<du>, 333f<du>))
            CG(8477, Glyph(482, 639f<du>, 688f<du>, 0f<du>, 0f<du>, 247f<du>)); CG(8484, Glyph(483, 667f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>))
            CG(8592, Glyph(222, 1000f<du>, 516f<du>, -16f<du>, 0f<du>, 500f<du>)); CG(8593, Glyph(226, 500f<du>, 688f<du>, -204f<du>, 0f<du>, 250f<du>))
            CG(8594, Glyph(223, 1000f<du>, 516f<du>, -16f<du>, 0f<du>, 500f<du>)); CG(8595, Glyph(227, 500f<du>, 704f<du>, -188f<du>, 0f<du>, 250f<du>))
            CG(8596, Glyph(228, 1000f<du>, 516f<du>, -16f<du>, 0f<du>, 500f<du>)); CG(8599, Glyph(229, 1000f<du>, 719f<du>, -204f<du>, 0f<du>, 500f<du>))
            CG(8600, Glyph(230, 1000f<du>, 704f<du>, -219f<du>, 0f<du>, 500f<du>)); CG(8614, Glyph(231, 977f<du>, 516f<du>, -16f<du>, 0f<du>, 488f<du>))
            CG(8635, Glyph(232, 771f<du>, 688f<du>, -63f<du>, 0f<du>, 385f<du>)); CG(8656, Glyph(233, 1000f<du>, 532f<du>, -32f<du>, 0f<du>, 500f<du>))
            CG(8658, Glyph(234, 1000f<du>, 532f<du>, -32f<du>, 0f<du>, 500f<du>)); CG(8660, Glyph(235, 1000f<du>, 532f<du>, -32f<du>, 0f<du>, 500f<du>))
            CG(8704, Glyph(433, 666f<du>, 688f<du>, 0f<du>, 0f<du>, 333f<du>)); CG(8706, Glyph(533, 586f<du>, 719f<du>, -32f<du>, 0f<du>, 291f<du>))
            CG(8707, Glyph(434, 556f<du>, 688f<du>, 0f<du>, 0f<du>, 278f<du>)); CG(8709, Glyph(435, 500f<du>, 782f<du>, -79f<du>, 0f<du>, 250f<du>))
            CG(8710, Glyph(535, 833f<du>, 719f<du>, 0f<du>, 0f<du>, 416f<du>)); CG(8711, Glyph(484, 833f<du>, 688f<du>, -32f<du>, 0f<du>, 416f<du>))
            CG(8712, Glyph(449, 667f<du>, 547f<du>, -47f<du>, 0f<du>, 333f<du>)); CG(8713, Glyph(451, 667f<du>, 735f<du>, -235f<du>, 0f<du>, 333f<du>))
            CG(8715, Glyph(450, 667f<du>, 547f<du>, -47f<du>, 0f<du>, 333f<du>)); CG(8722, Glyph(389, 778f<du>, 282f<du>, 218f<du>, 0f<du>, 389f<du>))
            CG(8723, Glyph(391, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>)); CG(8726, Glyph(403, 568f<du>, 610f<du>, -110f<du>, 0f<du>, 284f<du>))
            CG(8727, Glyph(401, 500f<du>, 469f<du>, 31f<du>, 0f<du>, 250f<du>)); CG(8728, Glyph(399, 412f<du>, 407f<du>, 93f<du>, 0f<du>, 206f<du>))
            CG(8733, Glyph(106, 778f<du>, 454f<du>, -16f<du>, 0f<du>, 389f<du>)); CG(8734, Glyph(103, 1000f<du>, 454f<du>, -16f<du>, 0f<du>, 500f<du>))
            CG(8736, Glyph(402, 778f<du>, 735f<du>, 0f<du>, 0f<du>, 389f<du>)); CG(8739, Glyph(404, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>))
            CG(8741, Glyph(405, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>)); CG(8743, Glyph(431, 667f<du>, 610f<du>, -32f<du>, 0f<du>, 333f<du>))
            CG(8744, Glyph(432, 667f<du>, 610f<du>, -32f<du>, 0f<du>, 333f<du>)); CG(8745, Glyph(425, 667f<du>, 610f<du>, -32f<du>, 0f<du>, 333f<du>))
            CG(8746, Glyph(426, 667f<du>, 610f<du>, -32f<du>, 0f<du>, 333f<du>)); CG(8756, Glyph(394, 516f<du>, 422f<du>, 78f<du>, 0f<du>, 258f<du>))
            CG(8757, Glyph(395, 516f<du>, 422f<du>, 78f<du>, 0f<du>, 258f<du>)); CG(8764, Glyph(452, 773f<du>, 375f<du>, 125f<du>, 0f<du>, 386f<du>))
            CG(8773, Glyph(453, 778f<du>, 563f<du>, 31f<du>, 0f<du>, 389f<du>)); CG(8776, Glyph(454, 773f<du>, 469f<du>, 31f<du>, 0f<du>, 386f<du>))
            CG(8800, Glyph(439, 778f<du>, 735f<du>, -235f<du>, 0f<du>, 389f<du>)); CG(8801, Glyph(440, 778f<du>, 469f<du>, 31f<du>, 0f<du>, 389f<du>))
            CG(8804, Glyph(441, 778f<du>, 641f<du>, -125f<du>, 0f<du>, 389f<du>)); CG(8805, Glyph(442, 778f<du>, 641f<du>, -125f<du>, 0f<du>, 389f<du>))
            CG(8810, Glyph(443, 1000f<du>, 547f<du>, -47f<du>, 0f<du>, 500f<du>)); CG(8811, Glyph(444, 1000f<du>, 547f<du>, -47f<du>, 0f<du>, 500f<du>))
            CG(8834, Glyph(445, 778f<du>, 547f<du>, -47f<du>, 0f<du>, 389f<du>)); CG(8835, Glyph(446, 778f<du>, 547f<du>, -47f<du>, 0f<du>, 389f<du>))
            CG(8838, Glyph(447, 778f<du>, 641f<du>, -141f<du>, 0f<du>, 389f<du>)); CG(8839, Glyph(448, 778f<du>, 641f<du>, -141f<du>, 0f<du>, 389f<du>))
            CG(8853, Glyph(437, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>)); CG(8855, Glyph(438, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>))
            CG(8869, Glyph(424, 778f<du>, 688f<du>, 0f<du>, 0f<du>, 389f<du>)); CG(8901, Glyph(393, 278f<du>, 313f<du>, 187f<du>, 0f<du>, 139f<du>))
            CG(8942, Glyph(396, 218f<du>, 594f<du>, -94f<du>, 0f<du>, 109f<du>)); CG(8943, Glyph(397, 776f<du>, 313f<du>, 187f<du>, 0f<du>, 388f<du>))
            CG(8945, Glyph(398, 613f<du>, 500f<du>, 0f<du>, 0f<du>, 306f<du>)); CG(8960, Glyph(436, 778f<du>, 610f<du>, -110f<du>, 0f<du>, 389f<du>))
            CG(8968, Glyph(255, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>)); CG(8969, Glyph(256, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>))
            CG(8970, Glyph(257, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>)); CG(8971, Glyph(258, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>))
            CG(9633, Glyph(457, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>)); CG(9651, Glyph(458, 968f<du>, 750f<du>, -16f<du>, 0f<du>, 484f<du>))
            CG(10216, Glyph(373, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>)); CG(10217, Glyph(374, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>))
            CG(10229, Glyph(224, 1463f<du>, 516f<du>, -16f<du>, 0f<du>, 731f<du>)); CG(10230, Glyph(225, 1463f<du>, 516f<du>, -16f<du>, 0f<du>, 731f<du>))
            CG(10234, Glyph(236, 1534f<du>, 532f<du>, -32f<du>, 0f<du>, 767f<du>))
        |]

/// Single glyphs the library refers to that no alphabet covers.
module Symbols =
    /// The upright d of a derivative, which is not a variable.
    let uprightD = Glyph(67, 556f<du>, 704f<du>, -16f<du>, 0f<du>, 377f<du>)

/// Operators whose codepoints are easy to mistake for the keys that resemble them.
module Operators =
    /// The plus sign.
    let plus = Glyph(11, 778f<du>, 594f<du>, -94f<du>, 0f<du>, 389f<du>)
    /// The minus sign, which is longer than the hyphen.
    let minus = Glyph(389, 778f<du>, 282f<du>, 218f<du>, 0f<du>, 389f<du>)
    /// The multiplication cross.
    let times = Glyph(400, 778f<du>, 500f<du>, 0f<du>, 0f<du>, 389f<du>)
    /// The division sign.
    let divide = Glyph(392, 778f<du>, 516f<du>, -16f<du>, 0f<du>, 389f<du>)
    /// The equals sign.
    let equals = Glyph(29, 778f<du>, 375f<du>, 125f<du>, 0f<du>, 389f<du>)
    /// The centred dot of a product.
    let cdot = Glyph(393, 278f<du>, 313f<du>, 187f<du>, 0f<du>, 139f<du>)

/// Accents, which are placed by the point they attach over.
module Accents =
    /// The circumflex of \hat.
    let hat = Glyph(239, 0f<du>, 735f<du>, 578f<du>, 0f<du>, -264f<du>)
    /// The tilde of \tilde.
    let tilde = Glyph(240, 0f<du>, 750f<du>, 546f<du>, 0f<du>, -264f<du>)
    /// The macron of \bar.
    let bar = Glyph(212, 0f<du>, 641f<du>, 609f<du>, 0f<du>, -263f<du>)
    /// The right arrow of \vec.
    let vec = Glyph(217, 0f<du>, 719f<du>, 515f<du>, 0f<du>, -264f<du>)
    /// The single dot of \dot, a first derivative in time.
    let dot = Glyph(213, 0f<du>, 688f<du>, 562f<du>, 0f<du>, -265f<du>)
    /// The double dot of \ddot, a second derivative in time.
    let doubleDot = Glyph(214, 0f<du>, 672f<du>, 578f<du>, 0f<du>, -261f<du>)
    /// The caron of \check.
    let check = Glyph(238, 0f<du>, 735f<du>, 578f<du>, 0f<du>, -264f<du>)
    /// The acute of \acute.
    let acute = Glyph(216, 0f<du>, 735f<du>, 546f<du>, 0f<du>, -233f<du>)
    /// The grave of \grave.
    let grave = Glyph(215, 0f<du>, 735f<du>, 546f<du>, 0f<du>, -295f<du>)
    /// The breve of \breve.
    let breve = Glyph(237, 0f<du>, 735f<du>, 593f<du>, 0f<du>, -264f<du>)

/// Delimiters, which grow to the height of what they hold.
module Delimiters =
    /// The opening round bracket.
    let roundLeft =
        StretchyGlyph(
            Glyph(8, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>),
            [|
                StretchSize(Glyph(8, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>), 997f<du>); StretchSize(Glyph(261, 422f<du>, 797f<du>, -297f<du>, 0f<du>, 211f<du>), 1095f<du>)
                StretchSize(Glyph(273, 458f<du>, 860f<du>, -360f<du>, 0f<du>, 229f<du>), 1195f<du>); StretchSize(Glyph(285, 523f<du>, 985f<du>, -485f<du>, 0f<du>, 261f<du>), 1445f<du>)
                StretchSize(Glyph(297, 597f<du>, 1157f<du>, -657f<du>, 0f<du>, 298f<du>), 1793f<du>); StretchSize(Glyph(309, 663f<du>, 1297f<du>, -797f<du>, 0f<du>, 331f<du>), 2093f<du>)
                StretchSize(Glyph(321, 736f<du>, 1454f<du>, -954f<du>, 0f<du>, 368f<du>), 2393f<du>); StretchSize(Glyph(333, 875f<du>, 1750f<du>, -1250f<du>, 0f<du>, 437f<du>), 2991f<du>)
            |],
            [|
                AssemblyPart(Glyph(335, 875f<du>, 1500f<du>, 0f<du>, 0f<du>, 437f<du>), 0f<du>, 249f<du>, 1495f<du>, false)
                AssemblyPart(Glyph(336, 875f<du>, 500f<du>, 0f<du>, 0f<du>, 437f<du>), 498f<du>, 498f<du>, 498f<du>, true)
                AssemblyPart(Glyph(337, 875f<du>, 1500f<du>, 0f<du>, 0f<du>, 437f<du>), 249f<du>, 0f<du>, 1495f<du>, false)
            |])
    /// The closing round bracket.
    let roundRight =
        StretchyGlyph(
            Glyph(9, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>),
            [|
                StretchSize(Glyph(9, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>), 997f<du>); StretchSize(Glyph(262, 422f<du>, 797f<du>, -297f<du>, 0f<du>, 211f<du>), 1095f<du>)
                StretchSize(Glyph(274, 458f<du>, 860f<du>, -360f<du>, 0f<du>, 229f<du>), 1195f<du>); StretchSize(Glyph(286, 523f<du>, 985f<du>, -485f<du>, 0f<du>, 261f<du>), 1445f<du>)
                StretchSize(Glyph(298, 597f<du>, 1157f<du>, -657f<du>, 0f<du>, 298f<du>), 1793f<du>); StretchSize(Glyph(310, 663f<du>, 1297f<du>, -797f<du>, 0f<du>, 331f<du>), 2093f<du>)
                StretchSize(Glyph(322, 736f<du>, 1454f<du>, -954f<du>, 0f<du>, 368f<du>), 2393f<du>); StretchSize(Glyph(334, 875f<du>, 1750f<du>, -1250f<du>, 0f<du>, 437f<du>), 2991f<du>)
            |],
            [|
                AssemblyPart(Glyph(338, 875f<du>, 1500f<du>, 0f<du>, 0f<du>, 437f<du>), 0f<du>, 249f<du>, 1495f<du>, false)
                AssemblyPart(Glyph(339, 875f<du>, 500f<du>, 0f<du>, 0f<du>, 437f<du>), 498f<du>, 498f<du>, 498f<du>, true)
                AssemblyPart(Glyph(340, 875f<du>, 1500f<du>, 0f<du>, 0f<du>, 437f<du>), 249f<du>, 0f<du>, 1495f<du>, false)
            |])
    /// The opening square bracket.
    let squareLeft =
        StretchyGlyph(
            Glyph(59, 278f<du>, 750f<du>, -250f<du>, 6f<du>, 139f<du>),
            [|
                StretchSize(Glyph(59, 278f<du>, 750f<du>, -250f<du>, 6f<du>, 139f<du>), 1001f<du>); StretchSize(Glyph(265, 340f<du>, 813f<du>, -313f<du>, 0f<du>, 170f<du>), 1101f<du>)
                StretchSize(Glyph(277, 417f<du>, 860f<du>, -360f<du>, 0f<du>, 208f<du>), 1201f<du>); StretchSize(Glyph(289, 444f<du>, 985f<du>, -485f<du>, 0f<du>, 222f<du>), 1451f<du>)
                StretchSize(Glyph(301, 472f<du>, 1157f<du>, -657f<du>, 4f<du>, 236f<du>), 1801f<du>); StretchSize(Glyph(313, 499f<du>, 1313f<du>, -813f<du>, 7f<du>, 249f<du>), 2101f<du>)
                StretchSize(Glyph(325, 528f<du>, 1454f<du>, -954f<du>, 9f<du>, 264f<du>), 2401f<du>); StretchSize(Glyph(351, 667f<du>, 1750f<du>, -1250f<du>, 8f<du>, 333f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(353, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 0f<du>, 500f<du>, 1500f<du>, false)
                AssemblyPart(Glyph(354, 667f<du>, 1000f<du>, 0f<du>, 0f<du>, 333f<du>), 1000f<du>, 1000f<du>, 1000f<du>, true)
                AssemblyPart(Glyph(355, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 500f<du>, 0f<du>, 1500f<du>, false)
            |])
    /// The closing square bracket.
    let squareRight =
        StretchyGlyph(
            Glyph(61, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>),
            [|
                StretchSize(Glyph(61, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>), 1001f<du>); StretchSize(Glyph(266, 340f<du>, 813f<du>, -313f<du>, 0f<du>, 170f<du>), 1101f<du>)
                StretchSize(Glyph(278, 417f<du>, 860f<du>, -360f<du>, 0f<du>, 208f<du>), 1201f<du>); StretchSize(Glyph(290, 444f<du>, 985f<du>, -485f<du>, 0f<du>, 222f<du>), 1451f<du>)
                StretchSize(Glyph(302, 472f<du>, 1157f<du>, -657f<du>, 0f<du>, 236f<du>), 1801f<du>); StretchSize(Glyph(314, 499f<du>, 1313f<du>, -813f<du>, 0f<du>, 249f<du>), 2101f<du>)
                StretchSize(Glyph(326, 528f<du>, 1454f<du>, -954f<du>, 0f<du>, 264f<du>), 2401f<du>); StretchSize(Glyph(352, 667f<du>, 1750f<du>, -1250f<du>, 0f<du>, 333f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(356, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 0f<du>, 500f<du>, 1500f<du>, false)
                AssemblyPart(Glyph(357, 667f<du>, 1000f<du>, 0f<du>, 0f<du>, 333f<du>), 1000f<du>, 1000f<du>, 1000f<du>, true)
                AssemblyPart(Glyph(358, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 500f<du>, 0f<du>, 1500f<du>, false)
            |])
    /// The opening curly bracket.
    let curlyLeft =
        StretchyGlyph(
            Glyph(90, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>),
            [|
                StretchSize(Glyph(90, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>), 1001f<du>); StretchSize(Glyph(263, 540f<du>, 813f<du>, -313f<du>, 0f<du>, 270f<du>), 1101f<du>)
                StretchSize(Glyph(275, 583f<du>, 860f<du>, -360f<du>, 0f<du>, 291f<du>), 1201f<du>); StretchSize(Glyph(287, 624f<du>, 985f<du>, -485f<du>, 0f<du>, 312f<du>), 1451f<du>)
                StretchSize(Glyph(299, 667f<du>, 1157f<du>, -657f<du>, 0f<du>, 333f<du>), 1801f<du>); StretchSize(Glyph(311, 707f<du>, 1313f<du>, -813f<du>, 0f<du>, 353f<du>), 2101f<du>)
                StretchSize(Glyph(323, 750f<du>, 1454f<du>, -954f<du>, 0f<du>, 375f<du>), 2401f<du>); StretchSize(Glyph(341, 902f<du>, 1750f<du>, -1250f<du>, 0f<du>, 451f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(343, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 0f<du>, 374f<du>, 750f<du>, false)
                AssemblyPart(Glyph(344, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 748f<du>, 748f<du>, 748f<du>, true)
                AssemblyPart(Glyph(345, 902f<du>, 1500f<du>, 0f<du>, 0f<du>, 451f<du>), 374f<du>, 374f<du>, 1500f<du>, false)
                AssemblyPart(Glyph(344, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 748f<du>, 748f<du>, 748f<du>, true)
                AssemblyPart(Glyph(346, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 374f<du>, 0f<du>, 750f<du>, false)
            |])
    /// The closing curly bracket.
    let curlyRight =
        StretchyGlyph(
            Glyph(92, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>),
            [|
                StretchSize(Glyph(92, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>), 1001f<du>); StretchSize(Glyph(264, 540f<du>, 813f<du>, -313f<du>, 0f<du>, 270f<du>), 1101f<du>)
                StretchSize(Glyph(276, 583f<du>, 860f<du>, -360f<du>, 0f<du>, 291f<du>), 1201f<du>); StretchSize(Glyph(288, 624f<du>, 985f<du>, -485f<du>, 0f<du>, 312f<du>), 1451f<du>)
                StretchSize(Glyph(300, 667f<du>, 1157f<du>, -657f<du>, 0f<du>, 333f<du>), 1801f<du>); StretchSize(Glyph(312, 707f<du>, 1313f<du>, -813f<du>, 0f<du>, 353f<du>), 2101f<du>)
                StretchSize(Glyph(324, 750f<du>, 1454f<du>, -954f<du>, 0f<du>, 375f<du>), 2401f<du>); StretchSize(Glyph(342, 902f<du>, 1750f<du>, -1250f<du>, 0f<du>, 451f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(347, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 0f<du>, 374f<du>, 750f<du>, false)
                AssemblyPart(Glyph(348, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 748f<du>, 748f<du>, 748f<du>, true)
                AssemblyPart(Glyph(349, 902f<du>, 1500f<du>, 0f<du>, 0f<du>, 451f<du>), 374f<du>, 374f<du>, 1500f<du>, false)
                AssemblyPart(Glyph(348, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 748f<du>, 748f<du>, 748f<du>, true)
                AssemblyPart(Glyph(350, 902f<du>, 750f<du>, 0f<du>, 0f<du>, 451f<du>), 374f<du>, 0f<du>, 750f<du>, false)
            |])
    /// The opening angle bracket, as a bra opens.
    let angleLeft =
        StretchyGlyph(
            Glyph(373, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>),
            [|
                StretchSize(Glyph(373, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>), 1001f<du>); StretchSize(Glyph(375, 428f<du>, 813f<du>, -313f<du>, 0f<du>, 214f<du>), 1101f<du>)
                StretchSize(Glyph(377, 472f<du>, 860f<du>, -360f<du>, 0f<du>, 236f<du>), 1201f<du>); StretchSize(Glyph(379, 537f<du>, 985f<du>, -485f<du>, 0f<du>, 268f<du>), 1451f<du>)
                StretchSize(Glyph(381, 611f<du>, 1157f<du>, -657f<du>, 0f<du>, 305f<du>), 1801f<du>); StretchSize(Glyph(383, 677f<du>, 1313f<du>, -813f<du>, 0f<du>, 338f<du>), 2101f<du>)
                StretchSize(Glyph(385, 750f<du>, 1454f<du>, -954f<du>, 0f<du>, 375f<du>), 2401f<du>); StretchSize(Glyph(387, 908f<du>, 1750f<du>, -1250f<du>, 0f<du>, 454f<du>), 3001f<du>)
            |],
            [||])
    /// The closing angle bracket, as a ket closes.
    let angleRight =
        StretchyGlyph(
            Glyph(374, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>),
            [|
                StretchSize(Glyph(374, 389f<du>, 750f<du>, -250f<du>, 0f<du>, 194f<du>), 1001f<du>); StretchSize(Glyph(376, 428f<du>, 813f<du>, -313f<du>, 0f<du>, 214f<du>), 1101f<du>)
                StretchSize(Glyph(378, 472f<du>, 860f<du>, -360f<du>, 0f<du>, 236f<du>), 1201f<du>); StretchSize(Glyph(380, 537f<du>, 985f<du>, -485f<du>, 0f<du>, 268f<du>), 1451f<du>)
                StretchSize(Glyph(382, 611f<du>, 1157f<du>, -657f<du>, 0f<du>, 305f<du>), 1801f<du>); StretchSize(Glyph(384, 677f<du>, 1313f<du>, -813f<du>, 0f<du>, 338f<du>), 2101f<du>)
                StretchSize(Glyph(386, 750f<du>, 1454f<du>, -954f<du>, 0f<du>, 375f<du>), 2401f<du>); StretchSize(Glyph(388, 908f<du>, 1750f<du>, -1250f<du>, 0f<du>, 454f<du>), 3001f<du>)
            |],
            [||])
    /// The opening floor bracket.
    let floorLeft =
        StretchyGlyph(
            Glyph(257, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>),
            [|
                StretchSize(Glyph(257, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>), 1001f<du>); StretchSize(Glyph(269, 458f<du>, 813f<du>, -313f<du>, 0f<du>, 229f<du>), 1101f<du>)
                StretchSize(Glyph(281, 472f<du>, 860f<du>, -360f<du>, 0f<du>, 236f<du>), 1201f<du>); StretchSize(Glyph(293, 499f<du>, 985f<du>, -485f<du>, 0f<du>, 249f<du>), 1451f<du>)
                StretchSize(Glyph(305, 528f<du>, 1157f<du>, -657f<du>, 0f<du>, 264f<du>), 1801f<du>); StretchSize(Glyph(317, 555f<du>, 1313f<du>, -813f<du>, 0f<du>, 277f<du>), 2101f<du>)
                StretchSize(Glyph(329, 583f<du>, 1454f<du>, -954f<du>, 0f<du>, 291f<du>), 2401f<du>); StretchSize(Glyph(361, 623f<du>, 1750f<du>, -1250f<du>, 0f<du>, 311f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(353, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 0f<du>, 500f<du>, 1500f<du>, false)
                AssemblyPart(Glyph(354, 667f<du>, 1000f<du>, 0f<du>, 0f<du>, 333f<du>), 1000f<du>, 1000f<du>, 1000f<du>, true)
            |])
    /// The closing floor bracket.
    let floorRight =
        StretchyGlyph(
            Glyph(258, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>),
            [|
                StretchSize(Glyph(258, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>), 1001f<du>); StretchSize(Glyph(270, 458f<du>, 813f<du>, -313f<du>, 0f<du>, 229f<du>), 1101f<du>)
                StretchSize(Glyph(282, 472f<du>, 860f<du>, -360f<du>, 0f<du>, 236f<du>), 1201f<du>); StretchSize(Glyph(294, 499f<du>, 985f<du>, -485f<du>, 0f<du>, 249f<du>), 1451f<du>)
                StretchSize(Glyph(306, 528f<du>, 1157f<du>, -657f<du>, 0f<du>, 264f<du>), 1801f<du>); StretchSize(Glyph(318, 555f<du>, 1313f<du>, -813f<du>, 0f<du>, 277f<du>), 2101f<du>)
                StretchSize(Glyph(330, 583f<du>, 1454f<du>, -954f<du>, 0f<du>, 291f<du>), 2401f<du>); StretchSize(Glyph(362, 623f<du>, 1750f<du>, -1250f<du>, 0f<du>, 311f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(356, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 0f<du>, 500f<du>, 1500f<du>, false)
                AssemblyPart(Glyph(357, 667f<du>, 1000f<du>, 0f<du>, 0f<du>, 333f<du>), 1000f<du>, 1000f<du>, 1000f<du>, true)
            |])
    /// The opening ceiling bracket.
    let ceilingLeft =
        StretchyGlyph(
            Glyph(255, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>),
            [|
                StretchSize(Glyph(255, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>), 1001f<du>); StretchSize(Glyph(267, 458f<du>, 813f<du>, -313f<du>, 0f<du>, 229f<du>), 1101f<du>)
                StretchSize(Glyph(279, 472f<du>, 860f<du>, -360f<du>, 0f<du>, 236f<du>), 1201f<du>); StretchSize(Glyph(291, 499f<du>, 985f<du>, -485f<du>, 0f<du>, 249f<du>), 1451f<du>)
                StretchSize(Glyph(303, 528f<du>, 1157f<du>, -657f<du>, 0f<du>, 264f<du>), 1801f<du>); StretchSize(Glyph(315, 555f<du>, 1313f<du>, -813f<du>, 0f<du>, 277f<du>), 2101f<du>)
                StretchSize(Glyph(327, 583f<du>, 1454f<du>, -954f<du>, 0f<du>, 291f<du>), 2401f<du>); StretchSize(Glyph(359, 623f<du>, 1750f<du>, -1250f<du>, 0f<du>, 311f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(354, 667f<du>, 1000f<du>, 0f<du>, 0f<du>, 333f<du>), 1000f<du>, 1000f<du>, 1000f<du>, true)
                AssemblyPart(Glyph(355, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 500f<du>, 0f<du>, 1500f<du>, false)
            |])
    /// The closing ceiling bracket.
    let ceilingRight =
        StretchyGlyph(
            Glyph(256, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>),
            [|
                StretchSize(Glyph(256, 444f<du>, 750f<du>, -250f<du>, 0f<du>, 222f<du>), 1001f<du>); StretchSize(Glyph(268, 458f<du>, 813f<du>, -313f<du>, 0f<du>, 229f<du>), 1101f<du>)
                StretchSize(Glyph(280, 472f<du>, 860f<du>, -360f<du>, 0f<du>, 236f<du>), 1201f<du>); StretchSize(Glyph(292, 499f<du>, 985f<du>, -485f<du>, 0f<du>, 249f<du>), 1451f<du>)
                StretchSize(Glyph(304, 528f<du>, 1157f<du>, -657f<du>, 0f<du>, 264f<du>), 1801f<du>); StretchSize(Glyph(316, 555f<du>, 1313f<du>, -813f<du>, 0f<du>, 277f<du>), 2101f<du>)
                StretchSize(Glyph(328, 583f<du>, 1454f<du>, -954f<du>, 0f<du>, 291f<du>), 2401f<du>); StretchSize(Glyph(360, 623f<du>, 1750f<du>, -1250f<du>, 0f<du>, 311f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(357, 667f<du>, 1000f<du>, 0f<du>, 0f<du>, 333f<du>), 1000f<du>, 1000f<du>, 1000f<du>, true)
                AssemblyPart(Glyph(358, 667f<du>, 1500f<du>, 0f<du>, 0f<du>, 333f<du>), 500f<du>, 0f<du>, 1500f<du>, false)
            |])
    /// The vertical bar of an absolute value, used on both sides.
    let bar =
        StretchyGlyph(
            Glyph(91, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>),
            [|
                StretchSize(Glyph(91, 278f<du>, 750f<du>, -250f<du>, 0f<du>, 139f<du>), 1001f<du>); StretchSize(Glyph(407, 278f<du>, 860f<du>, -360f<du>, 0f<du>, 139f<du>), 1203f<du>)
                StretchSize(Glyph(409, 278f<du>, 985f<du>, -485f<du>, 0f<du>, 139f<du>), 1445f<du>); StretchSize(Glyph(411, 278f<du>, 1125f<du>, -625f<du>, 0f<du>, 139f<du>), 1735f<du>)
                StretchSize(Glyph(413, 278f<du>, 1297f<du>, -797f<du>, 0f<du>, 139f<du>), 2085f<du>); StretchSize(Glyph(415, 278f<du>, 1500f<du>, -1000f<du>, 0f<du>, 139f<du>), 2503f<du>)
                StretchSize(Glyph(417, 278f<du>, 1766f<du>, -1266f<du>, 0f<du>, 139f<du>), 3005f<du>); StretchSize(Glyph(419, 278f<du>, 2063f<du>, -1563f<du>, 0f<du>, 139f<du>), 3607f<du>)
            |],
            [|
                AssemblyPart(Glyph(420, 278f<du>, 1204f<du>, 0f<du>, 0f<du>, 139f<du>), 0f<du>, 601f<du>, 1202f<du>, false)
                AssemblyPart(Glyph(421, 278f<du>, 1204f<du>, 0f<du>, 0f<du>, 139f<du>), 1202f<du>, 1202f<du>, 1202f<du>, true)
                AssemblyPart(Glyph(422, 278f<du>, 1204f<du>, 0f<du>, 0f<du>, 139f<du>), 601f<du>, 0f<du>, 1202f<du>, false)
            |])
    /// The slash of a division set on one line, used on both sides.
    let slash =
        StretchyGlyph(
            Glyph(15, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>),
            [|
                StretchSize(Glyph(15, 500f<du>, 750f<du>, -250f<du>, 0f<du>, 250f<du>), 1001f<du>); StretchSize(Glyph(406, 617f<du>, 907f<du>, -407f<du>, 0f<du>, 308f<du>), 1311f<du>)
                StretchSize(Glyph(408, 768f<du>, 1110f<du>, -610f<du>, 0f<du>, 384f<du>), 1717f<du>); StretchSize(Glyph(410, 964f<du>, 1375f<du>, -875f<du>, 0f<du>, 482f<du>), 2249f<du>)
                StretchSize(Glyph(412, 1222f<du>, 1735f<du>, -1235f<du>, 0f<du>, 611f<du>), 2945f<du>); StretchSize(Glyph(414, 1557f<du>, 2188f<du>, -1688f<du>, 0f<du>, 778f<du>), 3859f<du>)
                StretchSize(Glyph(416, 1997f<du>, 2782f<du>, -2282f<du>, 0f<du>, 998f<du>), 5055f<du>); StretchSize(Glyph(418, 2572f<du>, 3563f<du>, -3063f<du>, 0f<du>, 1286f<du>), 6621f<du>)
            |],
            [||])

/// Large operators, which take a taller glyph in display style and may carry limits.
module BigOperators =
    /// The summation sign.
    let sum =
        StretchyGlyph(
            Glyph(461, 1056f<du>, 750f<du>, -250f<du>, 0f<du>, 528f<du>),
            [|
                StretchSize(Glyph(461, 1056f<du>, 750f<du>, -250f<du>, 0f<du>, 528f<du>), 1001f<du>); StretchSize(Glyph(466, 1444f<du>, 954f<du>, -454f<du>, 0f<du>, 722f<du>), 1401f<du>)
            |],
            [||])
    /// The product sign.
    let product =
        StretchyGlyph(
            Glyph(462, 944f<du>, 750f<du>, -250f<du>, 0f<du>, 472f<du>),
            [|
                StretchSize(Glyph(462, 944f<du>, 750f<du>, -250f<du>, 0f<du>, 472f<du>), 1001f<du>); StretchSize(Glyph(467, 1278f<du>, 954f<du>, -454f<du>, 0f<du>, 639f<du>), 1401f<du>)
            |],
            [||])
    /// The coproduct sign.
    let coproduct =
        StretchyGlyph(
            Glyph(463, 944f<du>, 750f<du>, -250f<du>, 0f<du>, 472f<du>),
            [|
                StretchSize(Glyph(463, 944f<du>, 750f<du>, -250f<du>, 0f<du>, 472f<du>), 1001f<du>); StretchSize(Glyph(468, 1278f<du>, 954f<du>, -454f<du>, 0f<du>, 639f<du>), 1401f<du>)
            |],
            [||])
    /// The integral sign.
    let integral =
        StretchyGlyph(
            Glyph(459, 665f<du>, 813f<du>, -313f<du>, 332f<du>, 332f<du>),
            [|
                StretchSize(Glyph(459, 665f<du>, 813f<du>, -313f<du>, 332f<du>, 332f<du>), 1112f<du>); StretchSize(Glyph(464, 999f<du>, 1360f<du>, -860f<du>, 591f<du>, 499f<du>), 2223f<du>)
            |],
            [||])
    /// The contour integral sign.
    let contourIntegral =
        StretchyGlyph(
            Glyph(460, 665f<du>, 813f<du>, -313f<du>, 332f<du>, 332f<du>),
            [|
                StretchSize(Glyph(460, 665f<du>, 813f<du>, -313f<du>, 332f<du>, 332f<du>), 1112f<du>); StretchSize(Glyph(465, 999f<du>, 1360f<du>, -860f<du>, 591f<du>, 499f<du>), 2223f<du>)
            |],
            [||])
    /// The n-ary union sign.
    let union =
        StretchyGlyph(
            Glyph(429, 833f<du>, 750f<du>, -282f<du>, 0f<du>, 416f<du>),
            [|
                StretchSize(Glyph(429, 833f<du>, 750f<du>, -282f<du>, 0f<du>, 416f<du>), 1023f<du>); StretchSize(Glyph(430, 1111f<du>, 922f<du>, -438f<du>, 0f<du>, 555f<du>), 1357f<du>)
            |],
            [||])
    /// The n-ary intersection sign.
    let intersection =
        StretchyGlyph(
            Glyph(427, 833f<du>, 782f<du>, -250f<du>, 0f<du>, 416f<du>),
            [|
                StretchSize(Glyph(427, 833f<du>, 782f<du>, -250f<du>, 0f<du>, 416f<du>), 1023f<du>); StretchSize(Glyph(428, 1111f<du>, 938f<du>, -422f<du>, 0f<du>, 555f<du>), 1357f<du>)
            |],
            [||])

/// Roots, whose surd grows to cover the radicand.
module Radicals =
    /// The tick and bar of a root, which grows to cover the radicand.
    let surd =
        StretchyGlyph(
            Glyph(469, 833f<du>, 47f<du>, -969f<du>, 0f<du>, 416f<du>),
            [|
                StretchSize(Glyph(469, 833f<du>, 47f<du>, -969f<du>, 0f<du>, 416f<du>), 1001f<du>); StretchSize(Glyph(473, 1000f<du>, 860f<du>, -360f<du>, 0f<du>, 500f<du>), 1201f<du>)
                StretchSize(Glyph(474, 1000f<du>, 1157f<du>, -657f<du>, 0f<du>, 500f<du>), 1801f<du>); StretchSize(Glyph(475, 1000f<du>, 1454f<du>, -954f<du>, 0f<du>, 500f<du>), 2401f<du>)
                StretchSize(Glyph(476, 1000f<du>, 1750f<du>, -1250f<du>, 0f<du>, 500f<du>), 3001f<du>)
            |],
            [|
                AssemblyPart(Glyph(470, 1056f<du>, 1829f<du>, 0f<du>, 0f<du>, 528f<du>), 0f<du>, 320f<du>, 1820f<du>, false)
                AssemblyPart(Glyph(471, 1056f<du>, 641f<du>, 0f<du>, 0f<du>, 528f<du>), 640f<du>, 640f<du>, 640f<du>, true)
                AssemblyPart(Glyph(472, 1056f<du>, 625f<du>, 0f<du>, 0f<du>, 528f<du>), 320f<du>, 0f<du>, 620f<du>, false)
            |])

/// Marks that grow along the line to span what they are set over or under.
module HorizontalMarks =
    /// The circumflex of \widehat, which grows to cover its base.
    let wideHat =
        StretchyGlyph(
            Glyph(239, 0f<du>, 735f<du>, 578f<du>, 0f<du>, -264f<du>),
            [|
                StretchSize(Glyph(239, 0f<du>, 735f<du>, 578f<du>, 0f<du>, -264f<du>), 365f<du>); StretchSize(Glyph(241, 644f<du>, 750f<du>, 562f<du>, 0f<du>, 322f<du>), 645f<du>)
                StretchSize(Glyph(243, 768f<du>, 750f<du>, 562f<du>, 0f<du>, 384f<du>), 769f<du>); StretchSize(Glyph(245, 919f<du>, 750f<du>, 562f<du>, 0f<du>, 459f<du>), 920f<du>)
                StretchSize(Glyph(247, 1100f<du>, 750f<du>, 562f<du>, 0f<du>, 550f<du>), 1101f<du>); StretchSize(Glyph(249, 1320f<du>, 750f<du>, 562f<du>, 0f<du>, 660f<du>), 1321f<du>)
                StretchSize(Glyph(251, 1581f<du>, 750f<du>, 562f<du>, 0f<du>, 790f<du>), 1582f<du>); StretchSize(Glyph(253, 1896f<du>, 750f<du>, 562f<du>, 0f<du>, 948f<du>), 1897f<du>)
            |],
            [||])
    /// The tilde of \widetilde, which grows to cover its base.
    let wideTilde =
        StretchyGlyph(
            Glyph(240, 0f<du>, 750f<du>, 546f<du>, 0f<du>, -264f<du>),
            [|
                StretchSize(Glyph(240, 0f<du>, 750f<du>, 546f<du>, 0f<du>, -264f<du>), 371f<du>); StretchSize(Glyph(242, 652f<du>, 750f<du>, 546f<du>, 0f<du>, 326f<du>), 653f<du>)
                StretchSize(Glyph(244, 778f<du>, 766f<du>, 546f<du>, 0f<du>, 389f<du>), 779f<du>); StretchSize(Glyph(246, 931f<du>, 766f<du>, 531f<du>, 0f<du>, 465f<du>), 932f<du>)
                StretchSize(Glyph(248, 1115f<du>, 766f<du>, 531f<du>, 0f<du>, 557f<du>), 1116f<du>); StretchSize(Glyph(250, 1335f<du>, 766f<du>, 531f<du>, 0f<du>, 667f<du>), 1336f<du>)
                StretchSize(Glyph(252, 1599f<du>, 782f<du>, 531f<du>, 0f<du>, 799f<du>), 1600f<du>); StretchSize(Glyph(254, 1915f<du>, 782f<du>, 515f<du>, 0f<du>, 957f<du>), 1916f<du>)
            |],
            [||])
    /// The brace of \overbrace.
    let overbrace =
        StretchyGlyph(
            Glyph(259, 492f<du>, 782f<du>, 531f<du>, 28f<du>, 246f<du>),
            [|
                StretchSize(Glyph(259, 492f<du>, 782f<du>, 531f<du>, 28f<du>, 246f<du>), 493f<du>); StretchSize(Glyph(271, 993f<du>, 829f<du>, 500f<du>, 29f<du>, 496f<du>), 994f<du>)
                StretchSize(Glyph(283, 1494f<du>, 829f<du>, 500f<du>, 28f<du>, 747f<du>), 1495f<du>); StretchSize(Glyph(295, 1996f<du>, 829f<du>, 500f<du>, 28f<du>, 998f<du>), 1997f<du>)
                StretchSize(Glyph(307, 2498f<du>, 844f<du>, 500f<du>, 28f<du>, 1249f<du>), 2499f<du>); StretchSize(Glyph(319, 3000f<du>, 844f<du>, 500f<du>, 28f<du>, 1500f<du>), 3001f<du>)
                StretchSize(Glyph(331, 3502f<du>, 844f<du>, 484f<du>, 28f<du>, 1751f<du>), 3503f<du>); StretchSize(Glyph(363, 4006f<du>, 860f<du>, 484f<du>, 28f<du>, 2003f<du>), 4007f<du>)
            |],
            [|
                AssemblyPart(Glyph(365, 1002f<du>, 735f<du>, 484f<du>, 0f<du>, 501f<du>), 0f<du>, 497f<du>, 1002f<du>, false)
                AssemblyPart(Glyph(366, 994f<du>, 735f<du>, 609f<du>, 0f<du>, 497f<du>), 994f<du>, 994f<du>, 994f<du>, true)
                AssemblyPart(Glyph(367, 2003f<du>, 860f<du>, 609f<du>, 0f<du>, 1001f<du>), 497f<du>, 497f<du>, 2003f<du>, false)
                AssemblyPart(Glyph(366, 994f<du>, 735f<du>, 609f<du>, 0f<du>, 497f<du>), 994f<du>, 994f<du>, 994f<du>, true)
                AssemblyPart(Glyph(368, 1001f<du>, 735f<du>, 484f<du>, 0f<du>, 500f<du>), 497f<du>, 0f<du>, 1001f<du>, false)
            |])
    /// The brace of \underbrace.
    let underbrace =
        StretchyGlyph(
            Glyph(260, 492f<du>, -109f<du>, -360f<du>, 28f<du>, 246f<du>),
            [|
                StretchSize(Glyph(260, 492f<du>, -109f<du>, -360f<du>, 28f<du>, 246f<du>), 493f<du>); StretchSize(Glyph(272, 993f<du>, -78f<du>, -391f<du>, 28f<du>, 496f<du>), 994f<du>)
                StretchSize(Glyph(284, 1494f<du>, -78f<du>, -391f<du>, 28f<du>, 747f<du>), 1495f<du>); StretchSize(Glyph(296, 1996f<du>, -62f<du>, -407f<du>, 28f<du>, 998f<du>), 1997f<du>)
                StretchSize(Glyph(308, 2498f<du>, -62f<du>, -407f<du>, 28f<du>, 1249f<du>), 2499f<du>); StretchSize(Glyph(320, 3000f<du>, -62f<du>, -407f<du>, 28f<du>, 1500f<du>), 3001f<du>)
                StretchSize(Glyph(332, 3502f<du>, -62f<du>, -422f<du>, 28f<du>, 1751f<du>), 3503f<du>); StretchSize(Glyph(364, 4006f<du>, -62f<du>, -422f<du>, 28f<du>, 2003f<du>), 4007f<du>)
            |],
            [|
                AssemblyPart(Glyph(369, 1002f<du>, -62f<du>, -297f<du>, 0f<du>, 501f<du>), 0f<du>, 497f<du>, 1002f<du>, false)
                AssemblyPart(Glyph(370, 994f<du>, -187f<du>, -297f<du>, 0f<du>, 497f<du>), 994f<du>, 994f<du>, 994f<du>, true)
                AssemblyPart(Glyph(371, 2003f<du>, -187f<du>, -422f<du>, 0f<du>, 1001f<du>), 497f<du>, 497f<du>, 2003f<du>, false)
                AssemblyPart(Glyph(370, 994f<du>, -187f<du>, -297f<du>, 0f<du>, 497f<du>), 994f<du>, 994f<du>, 994f<du>, true)
                AssemblyPart(Glyph(372, 1001f<du>, -62f<du>, -297f<du>, 0f<du>, 500f<du>), 497f<du>, 0f<du>, 1001f<du>, false)
            |])
    /// The arrow of \overrightarrow.
    let rightArrow =
        StretchyGlyph(
            Glyph(217, 0f<du>, 719f<du>, 515f<du>, 0f<du>, -264f<du>),
            [|
                StretchSize(Glyph(217, 0f<du>, 719f<du>, 515f<du>, 0f<du>, -264f<du>), 417f<du>); StretchSize(Glyph(218, 659f<du>, 719f<du>, 515f<du>, 0f<du>, 329f<du>), 548f<du>)
            |],
            [|
                AssemblyPart(Glyph(219, 205f<du>, 641f<du>, 593f<du>, 0f<du>, 102f<du>), 0f<du>, 69f<du>, 205f<du>, false)
                AssemblyPart(Glyph(220, 137f<du>, 641f<du>, 593f<du>, 0f<du>, 68f<du>), 137f<du>, 137f<du>, 137f<du>, true)
                AssemblyPart(Glyph(221, 205f<du>, 719f<du>, 515f<du>, 0f<du>, 102f<du>), 69f<du>, 0f<du>, 205f<du>, false)
            |])

module internal FontFile =
    /// The math face, which every glyph but a blackboard bold capital comes from.
    let byteLength = 78608
    let sha256 = "2e09f6e03ccbc8e1d6e4cf16ff7a6fb629246144380baeff79ee472b542b2c86"
    /// The blackboard face.
    let blackboardByteLength = 8716
    let blackboardSha256 = "9578b5b9c86e6ab03846080b9d6fa4f7bc6b3044ac15604b8e7bfd4330295dda"
