<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="MathFontTypes.fs" />
    <Compile Include="MathFontData.g.fs" />
    <Compile Include="MathAtom.fs" />
    <Compile Include="MathFont.fs" />
    <Compile Include="Cursor.fs" />
    <Compile Include="Display.fs" />
    <Compile Include="Layout.fs" />
    <Compile Include="Painter.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="Summatic.FSUtils" Version="0.2.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ModeMath.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\fonts\latinmodern-math.otf" LogicalName="ModeMath.latinmodern-math.otf" />
  </ItemGroup>

</Project>
