module MathTableGen.Program

open System
open System.IO
open System.Security.Cryptography
open SkiaSharp

let private mathTag =
    uint32 (int 'M' <<< 24 ||| (int 'A' <<< 16) ||| (int 'T' <<< 8) ||| int 'H')

/// Codepoints outside the surrogate range, which no font maps.
let private allCodepoints =
    [|
        for c in 0x20 .. 0x10FFFF do
            if c < 0xD800 || c > 0xDFFF then yield c
    |]

let private writeConstants(w: Writer, table: MathTable, unitsPerEm: int) =
    w.Line "/// Positioning values from the MATH table, in font design units."
    w.Line "module MathConstants ="
    w.Line "    [<Literal>]"
    w.Line $"    let UnitsPerEm = {unitsPerEm}"
    for i in 0 .. MathConstantNames.table.Length - 1 do
        w.Line "    [<Literal>]"
        w.Line $"    let {MathConstantNames.table.[i]} = {table.Constants.[i]}"
    w.Line "    [<Literal>]"
    w.Line $"    let MinConnectorOverlap = {table.MinConnectorOverlap}"

let private writeConstructions(w: Writer, prefix: string, constructions: GlyphConstruction array) =
    let sizes = ResizeArray<string>()
    let parts = ResizeArray<string>()
    let rows = ResizeArray<string>()
    for construction in constructions do
        let sizeStart = sizes.Count
        for variant in construction.Variants do
            sizes.Add $"StretchSize({variant.Glyph}, {variant.Advance})"
        let partStart = parts.Count
        let italicCorrection =
            match construction.Assembly with
            | ValueNone -> 0
            | ValueSome assembly ->
                for part in assembly.Parts do
                    let extender = if part.IsExtender then "true" else "false"
                    parts.Add
                        $"AssemblyPart({part.Glyph}, {part.StartConnector}, {part.EndConnector}, \
                          {part.FullAdvance}, {extender})"
                assembly.ItalicsCorrection
        rows.Add
            $"StretchConstruction({construction.Glyph}, {sizeStart}, {construction.Variants.Length}, \
              {partStart}, {parts.Count - partStart}, {italicCorrection})"
    w.Array($"{prefix}Constructions", "StretchConstruction", rows)
    w.Array($"{prefix}Sizes", "StretchSize", sizes)
    w.Array($"{prefix}Parts", "AssemblyPart", parts)

[<EntryPoint>]
let main(args: string array): int =
    let fontPath = args.[0]
    let outputPath = args.[1]
    let fontBytes = File.ReadAllBytes fontPath
    use typeface = SKTypeface.FromFile fontPath
    let table = MathTable(typeface.GetTableData mathTag)
    if table.KernedGlyphCount > 0 then
        failwith $"{table.KernedGlyphCount} glyphs carry MathKernInfo, which is not generated"
    let unitsPerEm = typeface.UnitsPerEm
    let glyphCount = typeface.GlyphCount

    use font = new SKFont(typeface, float32 unitsPerEm)
    font.Hinting <- SKFontHinting.None
    font.Subpixel <- true

    let glyphIds = Array.init glyphCount uint16
    let widths = Array.zeroCreate<float32> glyphCount
    let bounds = Array.zeroCreate<SKRect> glyphCount
    font.GetGlyphWidths(ReadOnlySpan glyphIds, Span widths, Span bounds)

    let advances =
        widths
        |> Array.map (fun width ->
            if Math.Abs(width - MathF.Round width) > 0.01f then
                failwith $"Non-integral advance {width} at font size {unitsPerEm}"
            int (MathF.Round width))

    // Curve extrema land off the design grid, so bounds are rounded outwards.
    let lower(select: SKRect -> float32) = bounds |> Array.map (select >> floor >> int)
    let upper(select: SKRect -> float32) = bounds |> Array.map (select >> ceil >> int)

    let mapped = font.GetGlyphs(ReadOnlySpan allCodepoints)
    let cmap =
        [| for i in 0 .. allCodepoints.Length - 1 do
            if mapped.[i] <> 0us then yield allCodepoints.[i], int mapped.[i] |]

    let w = Writer()
    w.Line "namespace ModeMath"
    w.Blank()
    w.Line $"// Generated by tools/MathTableGen from {Path.GetFileName fontPath}. Do not edit."
    w.Blank()
    writeConstants(w, table, unitsPerEm)
    w.Blank()
    w.Line "module internal MathFontData ="
    w.Line $"    let fontByteLength = {fontBytes.Length}"
    w.Line $"    let fontSha256 = \"{Convert.ToHexStringLower(SHA256.HashData fontBytes)}\""
    w.Line $"    let glyphCount = {glyphCount}"
    let left = lower(fun b -> b.Left)
    let right = upper(fun b -> b.Right)
    let top = upper(fun b -> -b.Top)
    let bottom = lower(fun b -> -b.Bottom)
    w.Array("codepointGlyphs", "CG", cmap |> Seq.map (fun (c, g) -> $"CG({c}, {g})"))
    w.Array(
        "glyphMetrics",
        "GlyphMetrics",
        seq {
            for i in 0 .. glyphCount - 1 do
                yield $"GlyphMetrics({advances.[i]}, {left.[i]}, {right.[i]}, {top.[i]}, {bottom.[i]})"
        })
    w.Array(
        "italicCorrections",
        "ItalicCorrection",
        table.ItalicsCorrections |> Seq.map (fun (g, v) -> $"ItalicCorrection({g}, {v})"))
    w.Array(
        "topAccents",
        "TopAccent",
        table.TopAccentAttachments |> Seq.map (fun (g, v) -> $"TopAccent({g}, {v})"))
    w.Ints("extendedShapeGlyphs", table.ExtendedShapes)
    writeConstructions(w, "vertical", table.VerticalConstructions)
    writeConstructions(w, "horizontal", table.HorizontalConstructions)

    File.WriteAllText(outputPath, w.Text, Text.UTF8Encoding false)
    printfn $"{outputPath}: {glyphCount} glyphs, {cmap.Length} mapped codepoints, {w.Text.Length} bytes"
    0
