module MathTableGen.Program

open System
open System.IO
open System.Security.Cryptography
open SkiaSharp

let private mathTag =
    uint32 (int 'M' <<< 24 ||| (int 'A' <<< 16) ||| (int 'T' <<< 8) ||| int 'H')

/// Codepoints outside the surrogate range, which no font maps.
let private allCodepoints =
    [|
        for c in 0x20 .. 0x10FFFF do
            if c < 0xD800 || c > 0xDFFF then yield c
    |]

let private writeConstants(w: Writer, table: MathTable, unitsPerEm: int) =
    w.Line "/// Positioning values from the MATH table, in font design units."
    w.Line "module MathConstants ="
    w.Line "    [<Literal>]"
    w.Line $"    let UnitsPerEm = {unitsPerEm}"
    for i in 0 .. MathConstantNames.table.Length - 1 do
        w.Line "    [<Literal>]"
        w.Line $"    let {MathConstantNames.table.[i]} = {table.Constants.[i]}"
    w.Line "    [<Literal>]"
    w.Line $"    let MinConnectorOverlap = {table.MinConnectorOverlap}"

let private writeConstructions(w: Writer, prefix: string, constructions: GlyphConstruction array) =
    w.Array($"{prefix}Glyphs", constructions |> Array.map (fun c -> c.Glyph))
    let ends(counts: int seq) = Seq.scan (+) 0 counts
    w.Array($"{prefix}VariantStarts", ends(constructions |> Seq.map (fun c -> c.Variants.Length)))
    let variants = constructions |> Array.collect (fun c -> c.Variants)
    w.Array($"{prefix}VariantGlyphs", variants |> Array.map (fun v -> v.Glyph))
    w.Array($"{prefix}VariantAdvances", variants |> Array.map (fun v -> v.Advance))
    let parts(c: GlyphConstruction) =
        match c.Assembly with
        | ValueSome a -> a.Parts
        | ValueNone -> Array.empty
    w.Array($"{prefix}PartStarts", ends(constructions |> Seq.map (fun c -> (parts c).Length)))
    let allParts = constructions |> Array.collect parts
    w.Array($"{prefix}PartGlyphs", allParts |> Array.map (fun p -> p.Glyph))
    w.Array($"{prefix}PartStartConnectors", allParts |> Array.map (fun p -> p.StartConnector))
    w.Array($"{prefix}PartEndConnectors", allParts |> Array.map (fun p -> p.EndConnector))
    w.Array($"{prefix}PartFullAdvances", allParts |> Array.map (fun p -> p.FullAdvance))
    w.Array($"{prefix}PartExtenders", allParts |> Array.map (fun p -> if p.IsExtender then 1 else 0))
    w.Array(
        $"{prefix}AssemblyItalicsCorrections",
        constructions
        |> Array.map (fun c -> match c.Assembly with ValueSome a -> a.ItalicsCorrection | ValueNone -> 0))

[<EntryPoint>]
let main(args: string array): int =
    let fontPath = args.[0]
    let outputPath = args.[1]
    let fontBytes = File.ReadAllBytes fontPath
    use typeface = SKTypeface.FromFile fontPath
    let table = MathTable(typeface.GetTableData mathTag)
    if table.KernedGlyphCount > 0 then
        failwith $"{table.KernedGlyphCount} glyphs carry MathKernInfo, which is not generated"
    let unitsPerEm = typeface.UnitsPerEm
    let glyphCount = typeface.GlyphCount

    use font = new SKFont(typeface, float32 unitsPerEm)
    font.Hinting <- SKFontHinting.None
    font.Subpixel <- true

    let glyphIds = Array.init glyphCount uint16
    let widths = Array.zeroCreate<float32> glyphCount
    let bounds = Array.zeroCreate<SKRect> glyphCount
    font.GetGlyphWidths(ReadOnlySpan glyphIds, Span widths, Span bounds)

    let advances =
        widths
        |> Array.map (fun width ->
            if Math.Abs(width - MathF.Round width) > 0.01f then
                failwith $"Non-integral advance {width} at font size {unitsPerEm}"
            int (MathF.Round width))

    // Curve extrema land off the design grid, so bounds are rounded outwards.
    let lower(select: SKRect -> float32) = bounds |> Array.map (select >> floor >> int)
    let upper(select: SKRect -> float32) = bounds |> Array.map (select >> ceil >> int)

    let mapped = font.GetGlyphs(ReadOnlySpan allCodepoints)
    let cmap =
        [| for i in 0 .. allCodepoints.Length - 1 do
            if mapped.[i] <> 0us then yield allCodepoints.[i], int mapped.[i] |]

    let w = Writer()
    w.Line "namespace ModeMath"
    w.Blank()
    w.Line $"// Generated by tools/MathTableGen from {Path.GetFileName fontPath}. Do not edit."
    w.Blank()
    writeConstants(w, table, unitsPerEm)
    w.Blank()
    w.Line "module internal MathFontData ="
    w.Line $"    let fontByteLength = {fontBytes.Length}"
    w.Line $"    let fontSha256 = \"{Convert.ToHexStringLower(SHA256.HashData fontBytes)}\""
    w.Line $"    let glyphCount = {glyphCount}"
    w.Array("codepoints", cmap |> Array.map fst)
    w.Array("codepointGlyphs", cmap |> Array.map snd)
    w.Array("advances", advances)
    w.Array("boundsLeft", lower(fun b -> b.Left))
    w.Array("boundsRight", upper(fun b -> b.Right))
    w.Array("boundsTop", upper(fun b -> -b.Top))
    w.Array("boundsBottom", lower(fun b -> -b.Bottom))
    w.Array("italicsCorrectionGlyphs", table.ItalicsCorrections |> Array.map fst)
    w.Array("italicsCorrections", table.ItalicsCorrections |> Array.map snd)
    w.Array("topAccentGlyphs", table.TopAccentAttachments |> Array.map fst)
    w.Array("topAccentAttachments", table.TopAccentAttachments |> Array.map snd)
    w.Array("extendedShapeGlyphs", table.ExtendedShapes)
    writeConstructions(w, "vertical", table.VerticalConstructions)
    writeConstructions(w, "horizontal", table.HorizontalConstructions)

    File.WriteAllText(outputPath, w.Text, Text.UTF8Encoding false)
    printfn $"{outputPath}: {glyphCount} glyphs, {cmap.Length} mapped codepoints, {w.Text.Length} bytes"
    0
