<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Assert.fs" />
    <Compile Include="CursorTests.fs" />
    <Compile Include="MathFontTests.fs" />
    <Compile Include="LayoutTests.fs" />
    <Compile Include="PainterTests.fs" />
    <Compile Include="EditorTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SimpleTests" Version="0.2.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.151.1" />
    <PackageReference Include="Microsoft.Testing.Platform" Version="2.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModeMath\ModeMath.fsproj" />
  </ItemGroup>

</Project>
