module RenderExamples.Program

open System
open System.IO
open System.Text
open FSUtils
open ModeMath
open SkiaSharp

let private padding = 10f<px>
let private fontSize = 40f<px>

/// The whole pixels a length covers, which is where the measure comes off.
let private wholePixels(length: float32<px>) = max 1 (int (ceil (Measure.removeFloat32Unit<px> length)))

let private render(display: Placed, painter: Painter, path: string) =
    let width = wholePixels(display.Width + 2f * padding)
    let height = wholePixels(display.Height + 2f * padding)
    use bitmap = new SKBitmap(width, height)
    use canvas = new SKCanvas(bitmap)
    canvas.Clear SKColors.White
    use paint = new SKPaint(Color = SKColors.Black, IsAntialias = true)
    painter.Draw(display, canvas, padding, padding + display.Ascent, paint)
    use image = SKImage.FromBitmap bitmap
    use data = image.Encode(SKEncodedImageFormat.Png, 100)
    use file = File.Create path
    data.SaveTo file
    width, height

let private index(rendered: (string * int * int) list) =
    let text = StringBuilder()
    let line(s: string) = text.Append(s).Append("\r\n") |> ignore
    line "# Examples"
    line ""
    line $"Generated by `dotnet run --project tools/RenderExamples -- examples` at {fontSize} points."
    line ""
    line "| Name | Size | Rendering |"
    line "|---|---|---|"
    for name, width, height in rendered do
        line $"| {name} | {width}×{height} | ![{name}]({name}.png) |"
    line ""
    line "## Not yet expressible"
    line ""
    line "| Name | LaTeX | Waiting on |"
    line "|---|---|---|"
    for name, latex, waiting in Examples.unimplemented do
        let escaped = latex.Replace("|", "\\|")
        line $"| {name} | `{escaped}` | {waiting} |"
    text.ToString()

[<EntryPoint>]
let main(args: string array): int =
    let outputDirectory = args.[0]
    Directory.CreateDirectory outputDirectory |> ignore
    use painter = Painter.Embedded()
    let layout = Layout fontSize
    let rendered =
        [ for name, ma in Examples.implemented do
            let width, height =
                render(layout.Of ma, painter, Path.Combine(outputDirectory, name + ".png"))
            yield name, width, height ]
    File.WriteAllText(Path.Combine(outputDirectory, "README.md"), index rendered, UTF8Encoding false)
    printfn $"{rendered.Length} rendered, {Examples.unimplemented.Length} still to come"
    0
