module RenderExamples.Program

open System.IO
open System.Text
open FSUtils
open ModeMath
open SkiaSharp

let private padding = 10f<px>
let private fontSize = 40f<px>

/// The whole pixels a length covers, which is where the measure comes off.
let private wholePixels(length: float32<px>) = max 1 (int (ceil (Measure.removeFloat32Unit<px> length)))

let private render(display: Placed, painter: Painter, path: string) =
    let width = wholePixels(display.Width + 2f * padding)
    let height = wholePixels(display.Height + 2f * padding)
    use bitmap = new SKBitmap(width, height)
    use canvas = new SKCanvas(bitmap)
    canvas.Clear SKColors.White
    use paint = new SKPaint(Color = SKColors.Black, IsAntialias = true)
    painter.Draw(display, canvas, padding, padding + display.Ascent, paint)
    use image = SKImage.FromBitmap bitmap
    use data = image.Encode(SKEncodedImageFormat.Png, 100)
    use file = File.Create path
    data.SaveTo file
    width, height

let private renderCursor(editor: Editor, painter: Painter, path: string) =
    // The cursor stands taller than the formula, so the bitmap is sized to hold both.
    let bounds = editor.Bounds
    let width = wholePixels(bounds.Width + 2f * padding)
    let height = wholePixels(bounds.Thickness + 2f * padding)
    use bitmap = new SKBitmap(width, height)
    use canvas = new SKCanvas(bitmap)
    canvas.Clear SKColors.White
    use paint = new SKPaint(Color = SKColors.Black, IsAntialias = true)
    painter.Draw(
        editor.Cursor,
        canvas,
        padding - bounds.X,
        padding + bounds.Y + bounds.Thickness,
        paint)
    use image = SKImage.FromBitmap bitmap
    use data = image.Encode(SKEncodedImageFormat.Png, 100)
    use file = File.Create path
    data.SaveTo file
    width, height

let private index(rendered: (string * int * int) list, cursored: (string * int * int) list) =
    let text = StringBuilder()
    let line(s: string) = text.Append(s).Append("\r\n") |> ignore
    line "# Examples"
    line ""
    line
        $"Generated by `dotnet run --project tools/RenderExamples -- examples` at {fontSize.ToString()} pixels \
            to the em."
    line ""
    line "| Name | Size | Rendering |"
    line "|---|---|---|"
    for name, width, height in rendered do
        line $"| {name} | {width.ToString()}×{height.ToString()} | ![{name}]({name}.png) |"
    line ""
    line "## With the cursor"
    line ""
    line "| Name | Size | Rendering |"
    line "|---|---|---|"
    for name, width, height in cursored do
        line $"| {name} | {width.ToString()}×{height.ToString()} | ![{name}]({name}.png) |"
    line ""
    line "## Not yet expressible"
    line ""
    line "| Name | LaTeX | Waiting on |"
    line "|---|---|---|"
    for name, latex, waiting in Examples.unimplemented do
        let escaped = latex.Replace("|", "\\|")
        line $"| {name} | `{escaped}` | {waiting} |"
    text.ToString()

[<EntryPoint>]
let main(args: string array): int =
    let outputDirectory = args.[0]
    Directory.CreateDirectory outputDirectory |> ignore
    use painter = Painter.Embedded()
    let layout = Layout fontSize
    let rendered =
        [   for name, ma in Examples.implemented do
                let width, height =
                    render(layout.Of ma, painter, Path.Combine(outputDirectory, name + ".png"))
                yield name, width, height ]
    let cursored =
        [   for name, editor in Examples.cursored layout do
                let width, height =
                    renderCursor(editor, painter, Path.Combine(outputDirectory, name + ".png"))
                yield name, width, height ]
    File.WriteAllText(
        Path.Combine(outputDirectory, "README.md"),
        index(rendered, cursored),
        UTF8Encoding false)
    System.Console.WriteLine
        $"{rendered.Length.ToString()} rendered, {cursored.Length.ToString()} with the cursor, \
            {Examples.unimplemented.Length.ToString()} still to come"
    0
