"""Cuts the math face down to the glyphs ModeMath draws, and points the generated data at it.

Run from the repository root, after tools/MathTableGen and never before it:

    python -m pip install fonttools
    python tools/trimfont.py
"""

import hashlib
import re
import sys
from pathlib import Path

from fontTools import subset

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "fonts" / "latinmodern-math.otf"
TRIMMED = ROOT / "fonts" / "modemath-math.otf"
DATA = ROOT / "ModeMath" / "MathFontData.g.fs"

# A derived work under a name of its own, which the GUST licence asks for.
FAMILY = "ModeMath Math"
POSTSCRIPT = "ModeMathMath-Regular"

# The tables nothing reads: the painter draws by glyph id, and the metrics are generated already.
UNREAD = ["MATH", "GSUB", "GPOS", "GDEF", "FFTM"]

GLYPH = re.compile(r"Glyph\((\d+),")
GENERATED = (
    "// Generated by tools/MathTableGen from latinmodern-math.otf and "
    "AMS-Capital-Blackboard-Bold.otf. Do not edit."
)


def once(text, pattern, value, what):
    """Rewrites the one place something is written, any other count being a fault, not a warning."""
    rewritten, count = re.subn(pattern, lambda _: value, text)
    if count != 1:
        sys.exit(f"{DATA.name} holds {count} of {what}, not one")
    return rewritten


def rename(font):
    """The names the file answers to, leaving the copyright and trademark notices as they stand."""
    for record in font["name"].names:
        if record.nameID in (1, 16):
            record.string = FAMILY
        elif record.nameID in (4, 6):
            record.string = POSTSCRIPT
        elif record.nameID == 3:
            # The identifier a font cache keys on, which two faces may not share.
            record.string = f"{record};{POSTSCRIPT}"
    cff = font["CFF "].cff
    top = cff[cff.fontNames[0]]
    top.FullName = POSTSCRIPT
    top.FamilyName = FAMILY
    cff.fontNames[0] = POSTSCRIPT


def main():
    data = DATA.read_bytes().decode("utf-8")
    newline = "\r\n" if "\r\n" in data else "\n"
    source = SOURCE.read_bytes()
    if f'let sha256 = "{hashlib.sha256(source).hexdigest()}"' not in data:
        sys.exit(f"{DATA.name} was not generated from {SOURCE.name}: run MathTableGen over it first")

    ids = sorted({int(id) for id in GLYPH.findall(data)})
    options = subset.Options()
    options.drop_tables += UNREAD
    # Hints are kept: without them the same outlines rasterise differently.
    font = subset.load_font(str(SOURCE), options)
    before = list(font.getGlyphOrder())
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(gids=ids)
    subsetter.subset(font)
    rename(font)
    font.save(str(TRIMMED))

    after = {name: id for id, name in enumerate(font.getGlyphOrder())}
    dropped = [id for id in ids if before[id] not in after]
    if dropped:
        sys.exit(f"the subset left out glyphs {dropped}")
    trimmed = TRIMMED.read_bytes()
    data = GLYPH.sub(lambda m: f"Glyph({after[before[int(m.group(1))]]},", data)
    data = once(
        data,
        re.escape(GENERATED),
        "// Generated by tools/MathTableGen from latinmodern-math.otf and "
        f"AMS-Capital-Blackboard-Bold.otf,{newline}"
        "// then cut down to modemath-math.otf by tools/trimfont.py. Do not edit.",
        "the generated-from line",
    )
    data = once(data, r"let byteLength = \d+", f"let byteLength = {len(trimmed)}", "the byte length")
    data = once(
        data,
        r'let sha256 = "[0-9a-f]+"',
        f'let sha256 = "{hashlib.sha256(trimmed).hexdigest()}"',
        "the SHA-256",
    )
    DATA.write_bytes(data.encode("utf-8"))
    print(f"{len(ids)} glyphs of {len(before)}, {len(source):,} bytes down to {len(trimmed):,}")


main()
